/* ==========================================================================
   HOÀNG TỬ BÉ — DỮ LIỆU NỘI DUNG (book-data)
   Toàn bộ nội dung dưới đây là TÓM TẮT / DIỄN GIẢI viết lại bằng lời văn
   riêng của trang, không sao chép nguyên văn bản dịch có bản quyền.
   Nguồn: "book" = bám theo tác phẩm · "interpret" = diễn giải · "research" = tham khảo
   ========================================================================== */

const chapters = [
  { id: 0, roman: "", title: "Đề tặng", isSpecial: true,
    opening: "Trước khi câu chuyện bắt đầu, tác giả dừng lại một chút để nói một điều rất riêng tư.",
    summary: "Tác giả dành tặng cuốn sách này cho người bạn thân Léon Werth — với lời giải thích dí dỏm rằng ông tặng sách cho \"Léon Werth khi còn là một cậu bé\", vì mọi người lớn đều đã từng là trẻ con, chỉ là ít ai còn nhớ điều đó.",
    summaryLong: "Mở đầu cuốn sách không phải là một chương, mà là một lời đề tặng gửi cho Léon Werth — một người lớn. Tác giả nửa đùa nửa thật xin lỗi các em nhỏ vì điều đó, rồi lần lượt đưa ra ba lý do: đây là người bạn tốt nhất của ông, đây là người hiểu được cả sách viết cho trẻ em, và đây là người đang cần được an ủi. Nếu ba lý do ấy vẫn chưa đủ, ông chữa lại lời đề tặng: tặng cho Léon Werth khi còn là một cậu bé. Chỉ vài dòng ngắn ngủi, nhưng nó đã đặt ra toàn bộ tinh thần của cuốn sách — ý tưởng rằng mọi người lớn từng là trẻ con, chỉ là hầu hết đã quên mất điều đó.",
    events:["Vẽ bức tranh số 1 (con trăn nuốt voi nhìn từ ngoài)","Người lớn hiểu nhầm thành cái mũ","Vẽ bức tranh số 2 (nhìn xuyên qua bụng trăn) — người lớn vẫn không hiểu, khuyên cậu học Địa lý, Sử ký, Toán và Văn phạm","Từ bỏ nghề họa sĩ, trở thành phi công"],
    characters:["Người phi công (người kể chuyện)"], symbols:["Bức vẽ con trăn nuốt voi"],
    location:["📜 Lời mở đầu"], keywords:["đề tặng","tuổi thơ","người lớn"],
    importance:"Lời đề tặng là chiếc chìa khoá đọc toàn bộ cuốn sách: ranh giới giữa \"người lớn\" và \"trẻ con\" trong tác phẩm không nằm ở tuổi tác, mà ở việc còn nhớ hay đã quên đi cách nhìn của tuổi thơ.",
    reflection:"Một lời đề tặng tưởng như chỉ là nghi thức mở đầu, hoá ra lại là một lời mời: hãy đọc những trang sau bằng đôi mắt của đứa trẻ mà bạn đã từng là." },

  { id: 1, roman: "I", title: "Bức vẽ con trăn và con voi",
    opening: "Người kể chuyện mở đầu bằng một ký ức từ năm sáu tuổi — và một nỗi thất vọng đầu đời.",
    summary: "Người kể chuyện nhớ lại thời thơ ấu: cậu vẽ một con trăn vừa nuốt một con voi, nhưng người lớn nào nhìn vào cũng chỉ thấy đó là \"một cái mũ\". Chán nản vì không ai hiểu, cậu từ bỏ ước mơ trở thành họa sĩ và chọn học lái máy bay. Từ đó cậu quen sống giữa những người lớn thực tế, luôn phải giải thích mọi thứ bằng những điều \"dễ hiểu\" như số liệu thay vì hình ảnh.",
    summaryLong: "Hồi sáu tuổi, người kể chuyện xem một cuốn sách về rừng nguyên sinh có hình một con trăn đang nuốt trọn một con thú. Bị cuốn hút, cậu vẽ lại bức tranh của riêng mình — bức tranh số 1: một con trăn với hình dáng phồng to bí ẩn ở giữa. Đem khoe với người lớn, câu trả lời cậu nhận được luôn là: \"Sao lại phải sợ một cái mũ?\". Không nản lòng ngay, cậu vẽ tiếp bức tranh số 2, lần này vẽ xuyên qua bụng con trăn để mọi người thấy rõ con voi bên trong. Nhưng người lớn khuyên cậu nên gác việc vẽ vời sang một bên, tập trung học Địa lý, Sử ký, Toán và Văn phạm. Chính vì trải nghiệm đó, năm sáu tuổi cậu đã từ bỏ một sự nghiệp hoạ sĩ đầy hứa hẹn — và chọn học lái máy bay. Từ đó, cậu sống nhiều giữa những người lớn, thân cận với họ, và quan sát họ ở cự ly gần — nhưng vẫn giữ trong ngăn kéo hai bức vẽ đầu đời, thỉnh thoảng đem ra thử lòng những người mới gặp: nếu ai đó nhìn vào bức tranh số 1 mà không nói \"đó là một cái mũ\", cậu biết mình đã gặp một người có thể nói chuyện thật lòng.",
    characters:["Người phi công (người kể chuyện)"], symbols:["Bức vẽ con trăn nuốt voi"],
    location:["🎨 Ký ức tuổi thơ"], keywords:["tuổi thơ","hiểu lầm","người lớn"],
    importance:"Chương mở đầu đặt ra chủ đề xuyên suốt toàn tác phẩm: người lớn quen nhìn bằng lý trí và quy ước, nên bỏ lỡ những gì cần trí tưởng tượng để thấy. Nó cũng lý giải vì sao người kể chuyện, dù đã trưởng thành, vẫn giữ được một phần khả năng \"nhìn thấy\" — điều giúp anh trở thành người duy nhất tin lời Hoàng tử bé sau này.",
    reflection:"Một bức vẽ bị hiểu nhầm thành cái mũ nghe có vẻ là chuyện nhỏ của trẻ con, nhưng nó âm thầm quyết định cả một cuộc đời — và trở thành phép thử để nhận ra ai còn giữ được đôi mắt trẻ thơ." },

  { id: 2, roman: "II", title: "Sự cố giữa sa mạc Sahara",
    opening: "Sáu năm nghề phi công trôi qua, cho đến một buổi sáng giữa sa mạc, một giọng nói lạ vang lên.",
    summary: "Sáu năm sau, máy bay của người phi công gặp sự cố và rơi xuống sa mạc Sahara, cách nơi có người ở hàng ngàn dặm. Anh chỉ có đủ nước uống trong khoảng một tuần và phải tự sửa máy. Sáng hôm sau, một giọng nói kỳ lạ đánh thức anh: một cậu bé nhỏ nhắn đứng giữa sa mạc, nghiêm túc yêu cầu \"Xin ông vẽ cho tôi một con cừu!\".",
    summaryLong: "Đã sáu năm kể từ ký ức thời thơ ấu, người kể chuyện sống một mình, không có ai để nói chuyện thật lòng — cho đến khi máy bay của anh gặp sự cố động cơ và phải hạ cánh khẩn cấp giữa sa mạc Sahara, xa mọi khu dân cư hàng ngàn dặm. Không có thợ máy, không có hành khách, anh phải một mình cố sửa chữa với lượng nước chỉ đủ dùng trong khoảng một tuần. Đêm đầu tiên anh ngủ trên cát, kiệt sức hơn cả một người đắm tàu giữa đại dương. Nhưng đến lúc rạng sáng, một giọng nói kỳ lạ đánh thức anh dậy: \"Xin ông... vẽ cho tôi một con cừu!\". Trước mặt anh là một cậu bé nhỏ nhắn, kỳ dị, đứng giữa nơi không thể có sự sống nào — không khóc, không sợ hãi, không lạc lối, chỉ nghiêm túc chờ câu trả lời cho yêu cầu của mình. Ngạc nhiên đến mức không kịp phản ứng, người phi công đành vẽ đại vài hình con cừu theo trí nhớ hạn hẹp của mình — cho đến khi bất lực, anh vẽ lại bức tranh số 1 cũ, con trăn nuốt voi, chỉ để thử lòng. Và điều bất ngờ xảy ra: cậu bé nhận ra ngay đó không phải là con cừu, mà là một con trăn đang tiêu hoá một con voi.",
    characters:["Người phi công","Hoàng tử bé"], symbols:["Con cừu trong hộp","Sa mạc"],
    location:["🌵 Sa mạc Sahara"], keywords:["gặp gỡ","sa mạc","con cừu"],
    importance:"Đây là điểm khởi đầu thật sự của câu chuyện: hai kiểu \"người ngoài cuộc\" gặp nhau ở nơi không ai ngờ tới — một người lớn đang đối diện với cái chết có thể xảy đến, và một cậu bé đến từ nơi không ai biết. Việc Hoàng tử bé nhận ra ngay bức vẽ con trăn là dấu hiệu đầu tiên cho thấy cậu nhìn thế giới khác hẳn phần còn lại.",
    reflection:"Giữa nơi khắc nghiệt nhất, không phải nước hay động cơ máy bay, mà một câu hỏi ngây thơ về con cừu mới là điều khiến người phi công thực sự tỉnh táo trở lại." },

  { id: 3, roman: "III", title: "Hoàng tử bé đến từ đâu?",
    opening: "Phi công bắt đầu tò mò: cậu bé kỳ lạ này đến từ đâu, và vì sao lại xuất hiện giữa sa mạc?",
    summary: "Người phi công dần tò mò về xuất thân của cậu bé kỳ lạ này. Hoàng tử bé không trả lời trực tiếp các câu hỏi mà thường lặp lại câu hỏi của chính mình. Qua những chi tiết nhỏ — như việc cậu hỏi liệu con cừu có thể đi rất xa được không — phi công đoán rằng cậu đến từ một hành tinh rất nhỏ, nhỏ đến mức có thể đi quanh nó chỉ trong vài bước.",
    summaryLong: "Càng trò chuyện, phi công càng nhận ra Hoàng tử bé có một cách giao tiếp rất riêng: cậu không trả lời thẳng những câu hỏi được đặt ra, mà thường lặp lại chính câu hỏi ấy, như thể với cậu, những câu hỏi của mình quan trọng hơn câu trả lời của người khác. Từ những mảnh ghép rời rạc — cách cậu nhìn chiếc máy bay như \"con cừu chui ra từ đó\", cách cậu hỏi dồn dập liệu con cừu có thể đi bộ rất xa hay không, và nỗi lo lắng rằng ban đêm phải buộc dây cho cừu kẻo nó đi lạc — phi công dần đoán ra: Hoàng tử bé hẳn phải đến từ một nơi rất nhỏ, nhỏ đến mức không cần đi xa cũng có thể lạc mất. Đó là chương đầu tiên hé lộ rằng câu chuyện này sẽ không đi theo lối kể thông thường: người đọc, cũng như phi công, phải tự chắp nối manh mối để hiểu Hoàng tử bé, thay vì được kể thẳng ra mọi thứ.",
    events:["Hoàng tử bé hỏi về việc con cừu có ăn được cây bụi nhỏ không","Phi công nhận ra Hoàng tử bé đến từ một hành tinh rất nhỏ","Hoàng tử bé lo lắng liệu cừu có cần buộc dây ban đêm không"],
    characters:["Hoàng tử bé","Người phi công"], symbols:["Hành tinh nhỏ bé"],
    location:["🌵 Sa mạc Sahara"], keywords:["tò mò","hành tinh nhỏ","cách hỏi"],
    importance:"Chương này thiết lập cách kể chuyện đặc trưng của toàn tác phẩm: sự thật không được nói thẳng, mà được khám phá dần qua quan sát và suy luận — giống hệt cách người đọc phải \"nhìn bằng trái tim\" mới hiểu được những gì ẩn giấu phía sau lời nói.",
    reflection:"Một câu hỏi được lặp lại thay vì được trả lời hoá ra lại tiết lộ nhiều hơn bất kỳ câu trả lời trực tiếp nào." },

  { id: 4, roman: "IV", title: "Hành tinh B-612",
    opening: "Người kể chuyện dừng lại để tiết lộ một sự thật thiên văn học — và một điều ông áy náy về cách kể chuyện của chính mình.",
    summary: "Người kể chuyện tiết lộ rằng hành tinh quê hương của Hoàng tử bé chính là tiểu hành tinh mang tên B-612, từng được một nhà thiên văn Thổ Nhĩ Kỳ phát hiện nhưng không ai tin lời ông cho đến khi ông trình bày lại phát hiện trong bộ âu phục theo kiểu châu Âu. Tác giả cũng bộc bạch lý do ông không ghi rõ những con số như kích thước hành tinh ngay từ đầu: vì người lớn chỉ thực sự tin vào một câu chuyện khi nó đi kèm con số.",
    summaryLong: "Người kể chuyện tiết lộ điều mà anh đã đoán ra: hành tinh của Hoàng tử bé to chẳng hơn một ngôi nhà, và nó chính là tiểu hành tinh B-612 — từng được một nhà thiên văn học người Thổ Nhĩ Kỳ quan sát và công bố năm 1909, nhưng không một ai trong giới khoa học chịu tin, chỉ vì cách ăn mặc theo lối truyền thống của ông. Mãi đến khi một nhà độc tài Thổ Nhĩ Kỳ ra lệnh bắt buộc dân chúng ăn mặc kiểu châu Âu, nhà thiên văn học trình bày lại chính phát hiện cũ trong bộ âu phục lịch sự — và lần này mọi người tin ngay. Câu chuyện nhỏ này dẫn dắt tác giả đến một lời bộc bạch: ông cố tình không nói ngay từ đầu những con số cụ thể (kích thước hành tinh, tên gọi B-612), bởi ông biết người lớn chỉ thực sự tin một câu chuyện khi nó đi kèm những con số — tuổi tác của một người bạn mới, cân nặng, hay tiền bạc của cha mẹ họ — thay vì hỏi về giọng nói hay trò chơi yêu thích của người đó. Đây là lúc giọng văn châm biếm nhẹ nhàng của tác phẩm bắt đầu lộ rõ.",
    characters:["Nhà thiên văn học (Thổ Nhĩ Kỳ)"], symbols:["Hành tinh B-612","Những con số"],
    location:["🪐 B-612"], keywords:["con số","người lớn","niềm tin"],
    importance:"Chương IV là lời tuyên ngôn rõ ràng nhất của tác phẩm về cách người lớn đánh giá thế giới: bằng con số và hình thức bên ngoài, thay vì bằng bản chất. Nó cũng giải thích vì sao tác giả — người đang kể một câu chuyện cho người lớn đọc — lại chọn cách kể vòng vo, giàu hình ảnh thay vì thẳng vào dữ kiện.",
    reflection:"Cùng một sự thật, chỉ khác bộ trang phục trình bày, lại được tin hay bị nghi ngờ — một chi tiết hài hước nhưng cũng khá thật về cách người ta đánh giá điều gì đáng tin." },

  { id: 5, roman: "V", title: "Cây bao-bá",
    opening: "Mỗi buổi sáng trên hành tinh nhỏ bé của mình, Hoàng tử bé có một công việc không thể trì hoãn.",
    summary: "Hoàng tử bé kể về công việc mỗi sáng trên hành tinh của mình: nhổ bỏ những mầm cây bao-bá (baobab) ngay khi chúng còn nhỏ, vì nếu để chúng lớn lên, rễ cây có thể đâm xuyên và làm vỡ cả hành tinh nhỏ bé. Cậu nhấn mạnh rằng đó là một kỷ luật cần thiết, dù nhàm chán, để bảo vệ nơi mình sống.",
    summaryLong: "Hoàng tử bé kể cho phi công nghe về một mối nguy âm thầm trên hành tinh của cậu: hạt giống của cây bao-bá (baobab) — loại cây khổng lồ — có thể nằm lẫn trong đất mà không ai để ý, cho đến khi chúng nảy mầm. Nếu phát hiện sớm, chỉ cần nhổ bỏ như nhổ cỏ dại là xong; nhưng nếu chậm trễ, một khi cây đã lớn, không cách nào phá bỏ được nữa, và bộ rễ của nó có thể đâm xuyên, làm nứt vỡ cả hành tinh nhỏ bé. Vì vậy, mỗi sáng, ngay sau khi rửa mặt, việc đầu tiên Hoàng tử bé làm là kiểm tra kỹ hành tinh của mình để nhổ bỏ những mầm bao-bá còn non — một công việc nhàm chán, lặp đi lặp lại, nhưng cậu coi đó là kỷ luật bắt buộc. Người kể chuyện, xúc động trước sự nghiêm túc ấy, đã vẽ một bức tranh cảnh báo về một hành tinh bị bao-bá xâm chiếm hoàn toàn, với lời nhắn gửi tới trẻ em: hãy cẩn thận với bao-bá.",
    events:["Hoàng tử bé giải thích về việc nhổ cỏ và cây bao-bá mỗi ngày","Nếu bỏ mặc, cây bao-bá sẽ lớn nhanh và làm nứt vỡ hành tinh nhỏ","Người kể chuyện vẽ minh họa cảnh báo về hành tinh bị bao-bá xâm chiếm"],
    characters:["Hoàng tử bé"], symbols:["Cây bao-bá"],
    location:["🪐 B-612"], keywords:["kỷ luật","bao-bá","trì hoãn"],
    importance:"Bao-bá là một trong những hình ảnh được nhớ đến nhiều nhất của tác phẩm, vì nó biến một hành động nhỏ nhặt và lặp lại — nhổ cỏ mỗi sáng — thành một phép ẩn dụ cho việc phải đối diện sớm với những vấn đề có thể lớn dần nếu bị bỏ mặc.",
    reflection:"Một mầm cây trông vô hại hôm nay có thể là thứ làm nứt vỡ cả một thế giới nếu không ai để tâm đến nó kịp lúc." },

  { id: 6, roman: "VI", title: "Những buổi hoàng hôn",
    opening: "Có một thú vui riêng mà Hoàng tử bé chỉ tiết lộ vào đúng một ngày cậu đang rất buồn.",
    summary: "Hoàng tử bé kể rằng cậu rất thích ngắm hoàng hôn, và vì hành tinh của cậu quá nhỏ, chỉ cần dịch chuyển chiếc ghế vài bước là có thể xem mặt trời lặn bất cứ lúc nào cậu muốn. Có một ngày cậu đã ngắm hoàng hôn tới bốn mươi bốn lần liền — một chi tiết cậu tiết lộ khi đang rất buồn.",
    summaryLong: "Hoàng tử bé thổ lộ với phi công tình yêu của mình dành cho những buổi hoàng hôn — và một đặc quyền nhỏ mà chỉ hành tinh tí hon của cậu mới có: vì nó quá bé, cậu chỉ cần dịch chuyển chiếc ghế đi vài bước chân là có thể ngắm mặt trời lặn thêm một lần nữa, bất cứ khi nào mình muốn. Có một lần, cậu đã ngắm hoàng hôn tới bốn mươi bốn lần trong cùng một ngày. Điều khiến chi tiết này trở nên đáng nhớ không phải là con số, mà là hoàn cảnh cậu tiết lộ nó: khi được hỏi liệu đó có phải là ngày cậu rất buồn hay không, Hoàng tử bé không trả lời trực tiếp — sự im lặng của cậu đã nói thay tất cả. Người ta chỉ đi tìm hoàng hôn nhiều đến vậy khi lòng đang nặng trĩu một điều gì đó.",
    events:["Hoàng tử bé kể về thú vui ngắm hoàng hôn nhiều lần trong một ngày","Cậu tiết lộ đã xem 44 lần hoàng hôn trong một ngày buồn bã"],
    characters:["Hoàng tử bé"], symbols:["Hoàng hôn"],
    location:["🪐 B-612"], keywords:["hoàng hôn","nỗi buồn","cô đơn"],
    importance:"Đây là khoảnh khắc đầu tiên tác phẩm hé lộ nỗi buồn thầm lặng bên trong một nhân vật luôn tỏ ra ngây thơ, hồn nhiên — báo hiệu rằng phía sau những câu hỏi kỳ lạ của Hoàng tử bé là một câu chuyện tình cảm còn chưa được kể.",
    reflection:"Bốn mươi bốn lần hoàng hôn trong một ngày không phải là một trò chơi, mà là cách một cậu bé cô đơn tự an ủi mình khi không biết ngỏ lời cùng ai." },

  { id: 7, roman: "VII", title: "Điều gì thực sự quan trọng",
    opening: "Giữa lúc phi công đang vật lộn với chiếc máy bay hỏng, một câu hỏi bất ngờ khiến cả hai va chạm.",
    summary: "Khi phi công đang bận sửa máy bay và lo lắng về việc thiếu nước, Hoàng tử bé bất ngờ hỏi dồn về việc liệu cừu có ăn hoa có gai hay không. Phi công trả lời qua loa cho xong việc, khiến Hoàng tử bé giận dữ và khóc — với cậu, việc bảo vệ một bông hoa mà cậu yêu quý quan trọng hơn bất cứ con số hay cỗ máy nào của người lớn.",
    summaryLong: "Trong lúc phi công đang cặm cụi với con ốc vít cứng đầu của động cơ, đầu óc căng thẳng vì lượng nước ngày một cạn, Hoàng tử bé bất chợt hỏi một câu tưởng như vô nghĩa với hoàn cảnh: liệu cừu có ăn được cả những bông hoa có gai không. Bực bội vì bị làm phiền giữa lúc nguy cấp, phi công buông một câu trả lời cho có, thậm chí lỡ lời nói rằng gai chỉ là những thứ vô dụng, ác ý. Câu nói ấy khiến Hoàng tử bé sững lại rồi bật khóc — với cậu, câu hỏi ấy không hề nhỏ nhặt, vì đằng sau nó là một bông hoa cậu yêu quý, và việc con cừu có thể ăn mất bông hoa ấy là điều nghiêm trọng hơn bất cứ cỗ máy hay bất cứ con số nào của người lớn. Trước những giọt nước mắt ấy, phi công lần đầu nhận ra: thứ tưởng chừng ngây ngô của trẻ con lại có thể chứa đựng một điều nghiêm túc bậc nhất, còn thứ người lớn coi là cấp bách — máy móc, thời gian, sự sống còn — đôi khi lại không quan trọng bằng.",
    events:["Hoàng tử bé hỏi gay gắt về việc cừu có ăn hoa không","Phi công trả lời qua loa, thiếu kiên nhẫn","Hoàng tử bé bật khóc, tiết lộ cậu có một bông hoa rất quan trọng với mình"],
    characters:["Hoàng tử bé","Người phi công"], symbols:["Sự nghiêm túc của trẻ con","Bông hoa"],
    location:["🌵 Sa mạc Sahara"], keywords:["ưu tiên","bông hoa","thấu hiểu"],
    importance:"Chương bản lề nối liền hai phần của câu chuyện: nó khiến phi công — và người đọc — lần đầu thấy được chiều sâu cảm xúc phía sau Hoàng tử bé, mở đường cho chương tiếp theo kể về bông hoa hồng mà cậu đã bỏ lại.",
    reflection:"Có những giọt nước mắt không đến từ chuyện nhỏ, mà từ việc không ai chịu dừng lại đủ lâu để hiểu vì sao chuyện đó lại lớn đến vậy với người đang khóc." },

  { id: 8, roman: "VIII", title: "Bông hoa hồng",
    opening: "Từ đầu, mọi chuyện bắt đầu bằng một mầm cây khác thường nảy lên giữa hành tinh nhỏ bé.",
    summary: "Hoàng tử bé kể lại từ đầu: một ngày nọ, trên hành tinh của cậu nảy mầm một bông hoa xinh đẹp khác thường. Bông hoa kiêu hãnh, đỏng đảnh, hay phóng đại về bốn chiếc gai của mình như thể đó là vũ khí chống lại hổ báo — dù trên hành tinh bé nhỏ chẳng hề có loài thú nào. Hoàng tử bé chăm sóc bông hoa tận tình, nhưng những lời nói kiêu kỳ và mâu thuẫn của hoa khiến cậu dần cảm thấy mệt mỏi, nghi ngờ tình cảm của chính mình.",
    summaryLong: "Hoàng tử bé kể lại câu chuyện thật sự đằng sau giọt nước mắt của mình. Trên hành tinh của cậu vốn chỉ có những loài hoa bình thường, cho đến một ngày, một hạt giống lạ nảy mầm và lớn lên chậm rãi, thận trọng, như thể đang chuẩn bị cho một sự xuất hiện hoàn hảo. Khi cuối cùng nở ra, đó là một bông hồng lộng lẫy — nhưng cũng vô cùng kiêu hãnh và đỏng đảnh. Hoa yêu cầu được tưới nước đúng giờ, đòi có tấm chắn gió, và luôn phóng đại về bốn chiếc gai nhỏ của mình như thể chúng là vũ khí đủ sức chống lại hổ báo, dù hành tinh bé xíu ấy chẳng hề có một loài thú dữ nào. Hoàng tử bé, khi ấy còn quá non nớt để hiểu những lời lẽ mâu thuẫn ẩn giấu tình cảm thật, đã tận tâm chăm sóc bông hoa — nhưng những câu nói vừa yêu cầu vừa lảng tránh của hoa dần khiến cậu mệt mỏi, nghi ngờ liệu tình cảm mình dành cho hoa có đang bị lợi dụng hay không. Chính sự bối rối ấy, chứ không phải sự ghét bỏ, là điều đã âm thầm đẩy cậu đến quyết định rời đi ở chương sau.",
    events:["Bông hoa hồng nảy mầm và nở rộ, kiêu hãnh về vẻ đẹp của mình","Hoa nói về bốn chiếc gai như một sự phòng vệ","Hoàng tử bé tận tâm chăm sóc (tưới nước, che chắn) nhưng dần hoài nghi vì những lời lẽ mâu thuẫn của hoa"],
    characters:["Hoàng tử bé","Bông hoa hồng"], symbols:["Bông hoa hồng","Bốn chiếc gai"],
    location:["🪐 B-612"], keywords:["tình yêu","kiêu hãnh","hiểu lầm"],
    importance:"Đây là một trong những chương quan trọng nhất của tác phẩm: nó đặt nền cho toàn bộ chủ đề tình yêu, đồng thời cho thấy tình cảm thật thường bị che giấu sau những lời nói khó chịu — điều mà cả Hoàng tử bé lẫn người đọc chỉ hiểu rõ hơn về sau, qua lời con cáo." },

  { id: 9, roman: "IX", title: "Cuộc chia tay",
    opening: "Tổn thương vì những lời lẽ mâu thuẫn của hoa, Hoàng tử bé quyết định rời đi — nhưng phút chia tay lại không như cậu tưởng.",
    summary: "Cảm thấy tổn thương và bối rối trước những lời nói của bông hoa, Hoàng tử bé quyết định rời khỏi hành tinh để đi khám phá thế giới, tận dụng một đàn chim di cư hoang dã. Vào phút chia tay, bông hoa bất ngờ trở nên dịu dàng, xin lỗi vì đã khiến cậu buồn, và nói rằng mình yêu cậu — dù trước đó luôn giấu điều đó sau vẻ kiêu kỳ. Hoàng tử bé ra đi mang theo cảm giác day dứt.",
    summaryLong: "Trước ngày rời đi, Hoàng tử bé làm nốt những công việc quen thuộc: dọn dẹp các ngọn núi lửa (kể cả ngọn đã tắt, phòng khi nó bất ngờ hoạt động trở lại), nhổ những mầm bao-bá cuối cùng — những việc làm bình thường bỗng mang một nỗi buồn của lần cuối. Khi đến lúc chia tay bông hoa, cậu ngỡ sẽ ra đi trong ấm ức, nhưng bông hoa, lần đầu tiên, bỏ đi vẻ kiêu kỳ quen thuộc. Hoa xin lỗi vì đã khiến cậu buồn, thừa nhận mình đã ngốc nghếch, và cuối cùng nói thẳng điều mà trước giờ luôn giấu sau những đòi hỏi khó chịu: hoa yêu cậu. Hoa cũng từ chối chiếc chuông thuỷ tinh che chắn mà Hoàng tử bé định để lại, vì muốn tự đối mặt với thế giới — kể cả nếu có phải chịu vài con sâu bướm hay cơn gió lạnh. Hoàng tử bé rời đi cùng một đàn chim hoang dã di cư, mang theo cảm giác day dứt: cậu chỉ vừa kịp hiểu tình cảm thật của hoa đúng vào lúc phải nói lời tạm biệt.",
    events:["Hoàng tử bé chuẩn bị rời hành tinh, dọn dẹp núi lửa và nhổ bao-bá lần cuối","Cuộc trò chuyện chia tay xúc động với bông hoa","Bông hoa thể hiện tình cảm thật sự và để cậu ra đi"],
    characters:["Hoàng tử bé","Bông hoa hồng"], symbols:["Sự chia ly","Tình yêu ẩn sau kiêu hãnh"],
    location:["🪐 B-612"], keywords:["chia tay","tình yêu thật","ra đi"],
    importance:"Cuộc chia tay này gieo vào lòng Hoàng tử bé — và người đọc — câu hỏi sẽ đi theo suốt cuộc hành trình: điều gì thật sự làm nên giá trị của một mối gắn bó? Câu trả lời chỉ đến trọn vẹn ở chương về con cáo, gần cuối sách.",
    reflection:"Đôi khi người ta chỉ nói được lời yêu thương thật lòng đúng vào khoảnh khắc sắp phải xa nhau." },

  { id: 10, roman: "X", title: "Hành tinh của Nhà vua",
    opening: "Hành tinh đầu tiên trên hành trình của Hoàng tử bé chỉ có một người ở — và người đó tự cho mình quyền cai trị cả vũ trụ.",
    summary: "Hành tinh đầu tiên Hoàng tử bé ghé thăm chỉ có một vị vua cô độc, tự cho mình quyền cai trị cả vũ trụ. Ông ra lệnh cho mọi thứ — kể cả mặt trời — nhưng luôn khéo léo chỉ ra lệnh những điều vốn dĩ sẽ xảy ra, để lệnh của mình luôn được \"tuân theo\". Hoàng tử bé nhanh chóng nhận ra sự trống rỗng của thứ quyền lực không có ai để cai trị thật sự, và rời đi.",
    summaryLong: "Hành tinh đầu tiên trong sáu hành tinh Hoàng tử bé lần lượt ghé qua nhỏ đến mức chỉ vừa đủ chỗ cho một chiếc ngai vàng và tấm áo choàng của nhà vua. Ông chào đón cậu như một \"thần dân\" và tuyên bố mình có quyền trị vì cả vũ trụ, kể cả ra lệnh cho các vì sao. Khi Hoàng tử bé ngỏ ý muốn xem một cảnh hoàng hôn, nhà vua hứa sẽ \"ra lệnh\" cho mặt trời lặn — nhưng khéo léo dời thời điểm đến đúng lúc trời tự nhiên sẽ tối, để mệnh lệnh của ông luôn được tuân theo tuyệt đối. Bí quyết của ông, ông giải thích, là chỉ đòi hỏi những điều hợp lý, những điều bản thân sự vật vốn dĩ sẽ làm — quyền uy thật sự, theo ông, phải dựa trên lý lẽ chứ không phải áp đặt. Nhưng đằng sau vẻ uy nghiêm ấy là một sự thật trống rỗng: không có một thần dân nào khác để cai trị. Hoàng tử bé, sau khi xin phép rời đi vì cảm thấy chán, để lại phía sau một vị vua cô độc giữa vương quốc chỉ có chính mình.",
    events:["Nhà vua chào đón Hoàng tử bé như một \"thần dân\"","Nhà vua ra lệnh những điều hợp lý để luôn đúng","Hoàng tử bé xin phép rời đi vì cảm thấy chán"],
    characters:["Nhà vua"], symbols:["Quyền lực hình thức"], planet:"Hành tinh thứ nhất",
    location:["🪐 Hành tinh thứ nhất"], keywords:["quyền lực","cô đơn","hình thức"],
    importance:"Đây là hành tinh đầu tiên trong sáu \"chân dung người lớn\" — mở đầu cho một chuỗi châm biếm nhẹ nhàng về những cách người lớn tự giam mình trong một nỗi ám ảnh riêng, ở đây là quyền lực không có đối tượng để thực thi." },

  { id: 11, roman: "XI", title: "Hành tinh của Kẻ khoác lác",
    opening: "Hành tinh thứ hai chỉ có một người, và người ấy chỉ nghe được đúng một loại âm thanh.",
    summary: "Hành tinh thứ hai chỉ có một người đàn ông luôn muốn được ngưỡng mộ. Ông ta chỉ nghe thấy lời khen và diễn giải mọi hành động của Hoàng tử bé — kể cả việc bịt tai — thành một cử chỉ ngưỡng mộ dành cho mình. Hoàng tử bé nhanh chóng thấy chán nản trước sự cô đơn ẩn sau nhu cầu được tán dương ấy.",
    summaryLong: "Ở hành tinh thứ hai, Hoàng tử bé gặp một người đàn ông reo lên đầy phấn khích ngay khi thấy bóng dáng cậu từ xa: \"À! Một người ngưỡng mộ đến thăm ta!\". Với kẻ khoác lác này, mọi người khác trên đời chỉ tồn tại với một vai trò duy nhất: khán giả để tán thưởng mình. Ông yêu cầu Hoàng tử bé vỗ tay, rồi cất chiếc mũ nghiêng mình chào một cách trịnh trọng, lặp đi lặp lại. Khi Hoàng tử bé, chán nản, bịt tai lại vì tiếng ồn, kẻ khoác lác vẫn diễn giải cử chỉ ấy theo hướng có lợi cho mình — cho rằng đó cũng là một hình thức ngưỡng mộ. Ông tai chỉ có khả năng lọc lấy lời khen và bỏ ngoài mọi điều khác, kể cả những câu hỏi thẳng thắn của Hoàng tử bé. Rời khỏi hành tinh ấy, Hoàng tử bé tự nhủ với chính mình rằng người lớn quả thật rất kỳ lạ — nhưng ẩn sau lời nhận xét ngây thơ đó là một quan sát tinh tế: nhu cầu được ngưỡng mộ liên tục, đến mức không còn nghe được điều gì khác, cũng là một dạng cô đơn.",
    events:["Kẻ khoác lác yêu cầu Hoàng tử bé vỗ tay khen mình","Ông ta chỉ nghe được lời khen ngợi, bỏ ngoài tai mọi điều khác"],
    characters:["Kẻ khoác lác"], symbols:["Nhu cầu được ngưỡng mộ"], planet:"Hành tinh thứ hai",
    location:["🪐 Hành tinh thứ hai"], keywords:["ngưỡng mộ","cô đơn","tự mãn"],
    importance:"Nối tiếp hành tinh của nhà vua, chương này tiếp tục khắc hoạ một kiểu người lớn khác bị giam trong chính nhu cầu của bản thân — lần này là nhu cầu được công nhận, đến mức không còn khả năng lắng nghe người khác." },

  { id: 12, roman: "XII", title: "Hành tinh của Người nát rượu",
    opening: "Hành tinh thứ ba chỉ ghé qua trong chốc lát — nhưng để lại một trong những vòng luẩn quẩn kỳ lạ nhất tác phẩm.",
    summary: "Hành tinh thứ ba có một người đàn ông uống rượu để quên đi việc mình... uống rượu, và cảm thấy xấu hổ vì chính điều đó — một vòng luẩn quẩn không lối thoát. Hoàng tử bé rời đi trong sự bối rối, nhận ra rằng thế giới người lớn đôi khi thật kỳ lạ.",
    summaryLong: "Chuyến ghé thăm hành tinh thứ ba là chuyến thăm ngắn nhất nhưng cũng u ám nhất trong loạt sáu hành tinh. Hoàng tử bé thấy một người đàn ông ngồi lặng lẽ trước một hàng chai — vài chai rỗng, vài chai đầy. Khi được hỏi đang làm gì, ông trả lời: đang uống rượu. Khi được hỏi vì sao lại uống, ông trả lời: để quên đi. Quên đi điều gì? — để quên đi rằng mình đang xấu hổ. Xấu hổ vì điều gì? — xấu hổ vì uống rượu. Cuộc đối thoại khép lại thành một vòng tròn không lối ra: người đàn ông uống để quên đi chính hành động uống rượu của mình, và không có cách nào bước ra khỏi cái vòng lặp ấy. Hoàng tử bé rời đi trong im lặng, bối rối hơn bất kỳ hành tinh nào trước đó, và tự nhủ rằng thế giới của người lớn quả thực rất, rất kỳ lạ.",
    events:["Người nát rượu giải thích lý do uống rượu là để quên sự xấu hổ vì uống rượu"],
    characters:["Người nát rượu"], symbols:["Vòng luẩn quẩn"], planet:"Hành tinh thứ ba",
    location:["🪐 Hành tinh thứ ba"], keywords:["vòng luẩn quẩn","xấu hổ","trốn tránh"],
    importance:"Chương ngắn nhất trong loạt hành tinh lại là chương gây ám ảnh nhất, vì nó cho thấy một kiểu đau khổ không có nguyên nhân bên ngoài nào để đổ lỗi — con người đôi khi tự giam mình trong chính cách mình đang cố thoát ra." },

  { id: 13, roman: "XIII", title: "Hành tinh của Nhà tư sản",
    opening: "Hành tinh thứ tư thuộc về một người quá bận để ngẩng đầu lên, dù thứ ông đang đếm chính là bầu trời.",
    summary: "Hành tinh thứ tư thuộc về một doanh nhân bận rộn đếm các vì sao suốt ngày, tin rằng việc \"đếm được\" và \"ghi vào giấy\" đồng nghĩa với việc \"sở hữu\" chúng. Ông ta không có thời gian cho bất cứ điều gì khác ngoài những con số. Hoàng tử bé so sánh cách ông ta \"sở hữu\" các vì sao với cách chính cậu chăm sóc bông hoa và ngọn núi lửa của mình — và nhận ra sự khác biệt.",
    summaryLong: "Nhà tư sản trên hành tinh thứ tư bận rộn đến mức không ngẩng đầu lên nổi khi Hoàng tử bé đến, vì đang mải đếm — theo lời ông, đếm những vì sao. Ông giải thích logic của mình: khi tìm ra một vì sao chưa ai sở hữu, ông ghi số đó vào một tờ giấy, cất vào ngăn kéo và khoá lại — với ông, như vậy nghĩa là ông đã \"sở hữu\" nó. Hoàng tử bé, vốn quen với việc sở hữu một cách rất khác — cậu lau chùi những ngọn núi lửa, nhổ cỏ và tưới nước cho bông hoa của mình mỗi ngày — hỏi lại: việc ghi số lên giấy thì có ích gì cho những vì sao? Nhà tư sản không trả lời được câu hỏi đó, chỉ khăng khăng rằng đó là quyền sở hữu hợp pháp. Trong mắt Hoàng tử bé, cách \"sở hữu\" ấy trống rỗng — khác hẳn với việc cậu hữu ích cho bông hoa và núi lửa của mình bằng sự chăm sóc mỗi ngày, chứ không phải bằng một con số cất trong ngăn kéo.",
    events:["Nhà tư sản đếm và \"sở hữu\" các vì sao bằng cách ghi số lên giấy","Hoàng tử bé chỉ ra cậu \"hữu ích\" cho bông hoa và núi lửa của mình hơn là chỉ sở hữu con số"],
    characters:["Nhà tư sản"], symbols:["Sự sở hữu","Ám ảnh con số"], planet:"Hành tinh thứ tư",
    location:["🪐 Hành tinh thứ tư"], keywords:["sở hữu","con số","giá trị"],
    importance:"Chương này đối lập trực tiếp hai khái niệm \"sở hữu\": sở hữu bằng con số, giấy tờ (của nhà tư sản) và sở hữu bằng sự chăm sóc, trách nhiệm hằng ngày (của Hoàng tử bé) — chuẩn bị nền tảng cho ý niệm về \"thuần hoá\" sẽ xuất hiện ở chương con cáo." },

  { id: 14, roman: "XIV", title: "Hành tinh của Người thắp đèn",
    opening: "Hành tinh thứ năm nhỏ đến kỳ lạ — chỉ vừa đủ chỗ cho một cột đèn và một người tuân lệnh không ngừng nghỉ.",
    summary: "Hành tinh thứ năm nhỏ đến mức chỉ vừa đủ chỗ cho một cột đèn và người thắp đèn. Vì hành tinh quay ngày một nhanh, người này phải thắp rồi tắt đèn liên tục mỗi phút — một mệnh lệnh mà ông trung thành tuân theo dù kiệt sức. Trong mắt Hoàng tử bé, đây là người duy nhất trong số những người lớn cậu gặp mà cậu thấy có thể trở thành bạn, vì công việc của ông ít nhất còn có ý nghĩa với ai đó khác ngoài bản thân ông.",
    summaryLong: "Hành tinh thứ năm là hành tinh nhỏ nhất trong tất cả, chỉ vừa đủ chỗ cho một cột đèn đường và người thắp đèn của nó. Công việc của ông rất đơn giản trên lý thuyết: thắp đèn vào buổi tối, tắt đèn vào buổi sáng, theo đúng một mệnh lệnh cũ chưa từng được sửa đổi. Nhưng vì hành tinh quay ngày một nhanh hơn — trong khi mệnh lệnh vẫn giữ nguyên nhịp một ngày một đêm — ông buộc phải thắp rồi tắt đèn liên tục, cứ mỗi phút một lần, không một khoảnh khắc nghỉ ngơi. Dù kiệt sức, ông vẫn trung thành làm đúng phận sự, không một lời than vãn về sự vô lý của tình cảnh mình. Trong mắt Hoàng tử bé, đây là hành tinh đầu tiên có điều gì đó thật sự đẹp — vì đây là người duy nhất trong số những người lớn cậu từng gặp làm việc vì một điều gì đó khác ngoài bản thân mình. Cậu tiếc nuối vì hành tinh quá nhỏ, không đủ chỗ cho hai người, bởi đây là người cậu ước có thể kết bạn.",
    events:["Người thắp đèn thắp và tắt đèn liên tục theo mệnh lệnh cũ trong khi hành tinh quay ngày càng nhanh","Hoàng tử bé cảm thấy đây là người duy nhất không lố bịch, vì ông làm việc vì điều gì đó ngoài bản thân"],
    characters:["Người thắp đèn"], symbols:["Sự tận tụy","Công việc máy móc"], planet:"Hành tinh thứ năm",
    location:["🪐 Hành tinh thứ năm"], keywords:["tận tụy","mệnh lệnh","ý nghĩa công việc"],
    importance:"Người thắp đèn là nhân vật hiếm hoi trong chuỗi hành tinh được Hoàng tử bé — và tác phẩm — nhìn với thiện cảm, vì sự tận tụy của ông, dù máy móc và kiệt sức, vẫn hướng ra bên ngoài bản thân, khác hẳn những nỗi ám ảnh khép kín của các nhân vật trước." },

  { id: 15, roman: "XV", title: "Hành tinh của Nhà địa lý",
    opening: "Hành tinh thứ sáu lớn hơn hẳn — và ở đó, Hoàng tử bé gặp người sẽ chỉ đường cho cậu đến Trái Đất.",
    summary: "Hành tinh thứ sáu rộng lớn hơn hẳn, nơi một nhà địa lý già cả chuyên ghi chép về núi, sông, biển — nhưng lại chưa từng tự mình đi khảo sát bất cứ nơi nào, và cho rằng những thứ phù du như hoa không đáng để ghi vào bản đồ vì chúng không tồn tại mãi. Chính nhà địa lý là người gợi ý Hoàng tử bé nên ghé thăm Trái Đất — được ông đánh giá là \"khá nổi tiếng\".",
    summaryLong: "Hành tinh thứ sáu lớn hơn hẳn năm hành tinh trước, và ở đó có một nhà địa lý già cả, đang ngồi trước những cuốn sổ đồ sộ. Ông giải thích công việc của mình: ghi chép lại vị trí của những đại dương, sông ngòi, thành phố, núi non và sa mạc trên hành tinh — nhưng bản thân ông chưa từng một lần rời khỏi bàn làm việc để tự mình khảo sát, vì đó là việc của các nhà thám hiểm, không phải nhà địa lý. Khi Hoàng tử bé hào hứng muốn kể về bông hoa của mình, nhà địa lý từ chối ghi chép, giải thích rằng địa lý chỉ quan tâm đến những gì trường tồn, còn hoa chỉ là thứ \"phù du\", có thể biến mất bất cứ lúc nào. Câu trả lời ấy khiến Hoàng tử bé lần đầu tiên cảm nhận một nỗi lo mơ hồ cho bông hoa mình đã bỏ lại. Trước khi chia tay, chính nhà địa lý là người gợi ý cậu nên ghé thăm Trái Đất — một hành tinh, theo lời ông, \"khá nổi tiếng\" — mở ra chặng đường tiếp theo của hành trình.",
    events:["Nhà địa lý giải thích công việc ghi chép nhưng không tự mình khảo sát","Ông từ chối ghi lại bông hoa của Hoàng tử bé vì hoa là thứ \"phù du\"","Ông giới thiệu Hoàng tử bé đến thăm Trái Đất"],
    characters:["Nhà địa lý"], symbols:["Tri thức xa rời trải nghiệm"], planet:"Hành tinh thứ sáu",
    location:["🪐 Hành tinh thứ sáu"], keywords:["tri thức","phù du","trải nghiệm"],
    importance:"Lời từ chối ghi lại bông hoa là hạt giống đầu tiên gieo vào lòng Hoàng tử bé nỗi bất an về sự mong manh của những gì cậu yêu quý — cảm giác ấy sẽ lớn dần và bùng nổ khi cậu phát hiện khu vườn 5000 bông hồng ở Trái Đất.",
    reflection:"Một người biết rất nhiều về thế giới trên giấy tờ nhưng chưa từng thật sự chạm vào nó — và không nhận ra rằng chính những thứ \"phù du\" như một bông hoa mới là điều đáng ghi nhớ nhất." },

  { id: 16, roman: "XVI, XVII", title: "Trái Đất và con rắn",
    opening: "Trái Đất là hành tinh thứ bảy — và cũng là hành tinh lớn nhất, đông đúc nhất, nhưng lại vắng vẻ lạ thường nơi Hoàng tử bé đáp xuống.",
    summary: "Trái Đất là hành tinh thứ bảy Hoàng tử bé ghé thăm — nơi rộng lớn với vô số vua chúa, kẻ khoác lác, nhà tư sản và người lớn khác, nhưng vắng vẻ khi cậu đáp xuống giữa sa mạc. Ở đó cậu gặp một con rắn bí ẩn, nói năng như những câu đố, tự nhận mình có thể đưa bất cứ ai \"trở về\" nơi họ đến chỉ bằng một cái chạm — một lời gợi mở đầy ẩn ý cho phần kết của câu chuyện.",
    summaryLong: "Trái Đất không phải là một hành tinh bình thường: người kể chuyện liệt kê hàng loạt con số ấn tượng — hàng trăm nghìn nhà vua, hàng triệu kẻ khoác lác, hàng tỷ người lớn bận rộn — để nhấn mạnh quy mô khổng lồ của nơi này so với sáu hành tinh nhỏ bé trước đó. Vậy mà khi Hoàng tử bé đáp xuống, cậu lại rơi đúng vào giữa một sa mạc, không một bóng người. Ngỡ ngàng vì sự vắng vẻ trái ngược hoàn toàn với những gì được nghe kể, cậu gặp một con rắn — sinh vật đầu tiên lên tiếng, nhưng nói năng vòng vo như những câu đố. Con rắn tự nhận sức mạnh của mình lớn hơn cả một ngón tay của nhà vua, và có khả năng đưa bất cứ ai trở về nơi họ đã đến, chỉ bằng một cái chạm — một câu nói tưởng như vô hại lúc này, nhưng sẽ trở thành lời tiên báo cho những trang cuối cùng của cuốn sách. Cuộc gặp gỡ ngắn ngủi này khép lại trong một bầu không khí vừa tò mò vừa phảng phất điều gì đó không yên.",
    events:["Hoàng tử bé hạ cánh xuống sa mạc, ngỡ ngàng vì không thấy người","Gặp con rắn; con rắn nói những câu bí ẩn về sự cô đơn giữa loài người và khả năng đưa cậu \"về\" nơi cậu đến"],
    characters:["Con rắn"], symbols:["Con rắn","Sa mạc rộng lớn"], planet:"Trái Đất",
    location:["🌍 Trái Đất — sa mạc"], keywords:["Trái Đất","con rắn","cô đơn"],
    importance:"Chương này gieo một hạt giống quan trọng cho phần kết: lời hứa bí ẩn của con rắn về việc \"đưa ai đó trở về\" sẽ chỉ được hiểu trọn vẹn ở chương XXVI-XXVII, khi Hoàng tử bé thật sự tìm đến con rắn lần nữa." },

  { id: 17, roman: "XVIII, XIX, XX", title: "Ngọn núi và vườn hoa hồng",
    opening: "Trên hành trình băng qua sa mạc, Hoàng tử bé bước vào một khu vườn khiến toàn bộ niềm tin của cậu lung lay.",
    summary: "Hoàng tử bé băng qua sa mạc, gặp một bông hoa nhỏ ba cánh biết rất ít về con người, rồi trèo lên một đỉnh núi cao mong tìm được cái nhìn bao quát và có người để trò chuyện — nhưng chỉ nhận lại tiếng vọng của chính mình. Sau đó cậu tình cờ bước vào một khu vườn có đến năm nghìn bông hồng giống hệt bông hoa của mình. Phát hiện này khiến cậu suy sụp: cậu từng tin bông hoa của mình là duy nhất trong vũ trụ, hóa ra chỉ là một trong hàng ngàn bông hồng bình thường. Cậu nằm xuống cỏ và khóc.",
    summaryLong: "Tiếp tục băng qua sa mạc, Hoàng tử bé gặp một bông hoa nhỏ chỉ có ba cánh, sống đơn độc giữa cát và gần như không biết gì về con người ngoài việc từng thấy một đoàn thương nhân đi qua nhiều năm trước — hình ảnh gợi lên sự rộng lớn và trống trải của thế giới loài người. Mong tìm được ai đó để trò chuyện, cậu trèo lên một đỉnh núi cao, hy vọng từ đó có thể nhìn thấy toàn bộ hành tinh và mọi con người trên đó — như cách cậu có thể ngắm trọn hành tinh bé nhỏ của mình chỉ trong vài bước chân. Nhưng thứ duy nhất đáp lại lời chào của cậu chỉ là tiếng vọng của chính giọng nói mình, lặp đi lặp lại giữa những vách đá lạnh lẽo. Rồi, đi tiếp, cậu tình cờ bước vào một khu vườn hoa hồng — nơi có đến năm nghìn bông hồng nở rộ, tất cả đều giống hệt bông hoa cậu đã để lại trên B-612. Cú sốc ập đến ngay lập tức: cậu từng tin rằng mình sở hữu một bông hoa có một không hai trong cả vũ trụ, hoá ra đó chỉ là một bông hồng bình thường trong hàng ngàn bông hồng giống hệt nhau. Cậu nằm gục xuống cỏ và khóc — không phải vì ghét bỏ hoa của mình, mà vì cảm thấy mình đã bị lừa dối bởi chính những gì hoa từng nói, và vì nhận ra một điều đau đớn: làm một hoàng tử của một bông hoa như thế chẳng khiến cậu trở nên giàu có hay đặc biệt như cậu từng nghĩ.",
    events:["Gặp bông hoa ba cánh giữa sa mạc","Trèo núi cao, chỉ nghe thấy tiếng vọng","Phát hiện vườn có 5000 bông hồng giống hệt hoa của mình","Hoàng tử bé đau khổ, nghĩ mình chỉ sở hữu một bông hồng bình thường"],
    characters:["Hoàng tử bé","Những bông hồng trong vườn"], symbols:["Vườn hoa hồng","Sự đơn độc giữa đám đông giống nhau"], planet:"Trái Đất",
    location:["🌍 Trái Đất — núi và vườn hồng"], keywords:["vườn hồng","vỡ mộng","sự duy nhất"],
    importance:"Đây là điểm khủng hoảng cảm xúc sâu nhất của Hoàng tử bé trước khi gặp cáo — sự sụp đổ của niềm tin rằng bông hoa của mình là duy nhất chính là lý do khiến bài học của con cáo, ngay sau đó, có sức nặng lớn đến vậy: nó không chỉ dạy một khái niệm, mà chữa lành một vết thương vừa mới xảy ra.",
    reflection:"Phát hiện ra rằng điều mình từng nghĩ là duy nhất hoá ra rất đỗi bình thường là một trong những cú sốc lớn nhất của việc trưởng thành — và cũng là bước ngoặt cần thiết trước khi hiểu được điều gì thật sự làm nên sự duy nhất." },

  { id: 18, roman: "XXI", title: "Con cáo — Thuần hóa",
    opening: "Giữa lúc đang buồn bã nhất, Hoàng tử bé gặp một sinh vật sẽ thay đổi hoàn toàn cách cậu nhìn về bông hoa của mình.",
    summary: "Giữa lúc buồn bã, Hoàng tử bé gặp một con cáo và ngỏ ý muốn chơi cùng. Cáo từ chối vì \"chưa được thuần hóa\", rồi giải thích: thuần hóa nghĩa là \"tạo ra những mối dây ràng buộc\" — trước khi thuần hóa nhau, hai bên chỉ là hàng vạn con cáo hay hàng vạn cậu bé giống nhau; nhưng một khi đã thuần hóa, họ trở nên cần thiết với nhau, duy nhất trên đời đối với nhau. Cáo xin Hoàng tử bé thuần hóa mình và hướng dẫn cách làm: kiên nhẫn, đến vào cùng một giờ mỗi ngày, ngồi lại gần nhau dần dần, không vội vàng bằng lời nói.\n\nQua quá trình đó, cáo giúp Hoàng tử bé hiểu ra: chính thời gian và sự chăm sóc cậu dành cho bông hoa của mình đã khiến nó trở nên đặc biệt và duy nhất — không phải vì nó khác biệt so với 5000 bông hồng kia, mà vì cậu đã \"mất thì giờ\" vì nó. Trước khi chia tay, cáo tặng cậu một bí mật: \"Người ta chỉ nhìn rõ với trái tim. Cái cốt yếu thì con mắt không thấy được\", và nhắc cậu rằng cậu mãi mãi có trách nhiệm với những gì mình đã thuần hóa.",
    summaryLong: "Ngồi khóc dưới gốc cây hồng, Hoàng tử bé gặp một con cáo và rủ nó cùng chơi cho khuây khoả. Con cáo từ chối, giải thích rằng nó chưa được \"thuần hoá\" — một từ mà Hoàng tử bé chưa từng nghe. Cáo giải thích: thuần hoá nghĩa là \"tạo ra những mối dây ràng buộc\". Trước khi được thuần hoá, cáo chỉ là một trong hàng vạn con cáo giống hệt nhau, chẳng có ý nghĩa gì đặc biệt với Hoàng tử bé, và ngược lại, cậu cũng chỉ là một trong hàng vạn cậu bé đối với cáo. Nhưng nếu thuần hoá nhau, họ sẽ trở nên cần thiết với nhau, duy nhất đối với nhau trên toàn thế giới. Bị thuyết phục, cáo xin được thuần hoá và hướng dẫn cách làm — không phải bằng lời nói vội vàng, mà bằng sự kiên nhẫn: ngồi cách nhau một khoảng, xích lại gần dần mỗi ngày, và quan trọng nhất là đến vào đúng một giờ cố định, để cáo có thể chuẩn bị trái tim mình từ sớm, càng gần giờ hẹn càng thấy hạnh phúc hơn. Qua nhiều ngày như vậy, mối dây ràng buộc dần hình thành. Và chính từ tình bạn ấy, cáo giúp Hoàng tử bé nhìn lại vườn hồng bằng con mắt khác: năm nghìn bông hồng kia đẹp, nhưng trống rỗng, vì chưa ai thuần hoá chúng; còn bông hoa trên B-612, dù chỉ là một bông hồng bình thường như bao bông khác, lại trở thành duy nhất trong toàn vũ trụ — chính vì Hoàng tử bé đã dành thời gian tưới nước, che chắn gió, lắng nghe cả những lời than phiền của nó. Trước phút chia tay đầy xúc động, cáo tặng cậu một bí mật để mang theo suốt đời: \"Người ta chỉ nhìn thấy rõ với trái tim. Cái cốt yếu thì con mắt không nhìn thấy được\" — và nhắc cậu rằng, một khi đã thuần hoá điều gì, người ta mãi mãi có trách nhiệm với nó.",
    events:["Hoàng tử bé gặp cáo, cáo giải thích khái niệm \"thuần hóa\"","Cáo hướng dẫn cách thuần hóa: kiên nhẫn, đều đặn, từ từ","Hoàng tử bé thuần hóa cáo qua nhiều ngày","Cáo giúp cậu nhận ra giá trị thật sự của bông hoa mình","Cáo tặng bí mật: nhìn bằng trái tim; và nhắc về trách nhiệm với điều mình đã gắn bó","Cuộc chia tay đầy xúc động giữa hai người bạn"],
    characters:["Hoàng tử bé","Con cáo"], symbols:["Sự thuần hóa","Nhìn bằng trái tim","Trách nhiệm"], planet:"Trái Đất",
    location:["🌍 Trái Đất"], keywords:["thuần hoá","tình bạn","trách nhiệm","nhìn bằng trái tim"],
    importance:"Đây là chương trung tâm của toàn tác phẩm — nơi mọi mảnh ghép trước đó (bông hoa, vườn hồng, nỗi cô đơn của các người lớn) được kết nối lại thành một thông điệp thống nhất về tình yêu, tình bạn và trách nhiệm. Câu nói của cáo trở thành câu nói được nhớ đến nhiều nhất trong toàn bộ cuốn sách." },

  { id: 19, roman: "XXII, XXIII", title: "Người gác ghi và người lái buôn",
    opening: "Hai cuộc gặp ngắn ngủi trên đường đi hé lộ thêm một khía cạnh khác trong cách người lớn sống với thời gian.",
    summary: "Hoàng tử bé tiếp tục cuộc hành trình và gặp một người gác ghi đường sắt, người điều phối những đoàn tàu chở đầy hành khách vội vã lao từ nơi này sang nơi khác mà không ai thực sự biết mình tìm kiếm điều gì — chỉ có trẻ con là còn áp mặt vào cửa kính để ngắm nhìn thế giới. Sau đó cậu gặp một người lái buôn bán loại viên thuốc \"giải khát\" giúp người ta tiết kiệm được 53 phút mỗi tuần vì không cần uống nước — Hoàng tử bé nhận xét rằng nếu là mình, cậu thà dùng 53 phút đó để thong thả đi đến một dòng suối.",
    summaryLong: "Người gác ghi đường sắt kể cho Hoàng tử bé nghe về công việc điều phối những đoàn tàu tốc hành chở đầy hành khách, ngày đêm lao vun vút từ nơi này sang nơi khác. Điều kỳ lạ là những hành khách ấy luôn vội vã, nhưng khi được hỏi, không ai trong số họ thực sự biết rõ mình đang tìm kiếm điều gì — họ chỉ đơn giản là tiếp tục di chuyển, đoàn tàu này nối đoàn tàu khác. Chỉ có duy nhất bọn trẻ con là còn áp sát mặt vào cửa kính toa tàu, say sưa ngắm nhìn cảnh vật lướt qua, thay vì ngủ gật như người lớn. Rời khỏi đó, Hoàng tử bé gặp một người lái buôn bán một loại thuốc viên đặc biệt: uống một viên là hết khát cả tuần, giúp tiết kiệm được năm mươi ba phút vốn dùng để uống nước. Khi được hỏi năm mươi ba phút ấy dùng để làm gì, người lái buôn trả lời: tuỳ mỗi người muốn dùng vào việc gì cũng được. Hoàng tử bé, sau một thoáng suy nghĩ, tự nhủ rằng nếu là mình, cậu thà dùng trọn năm mươi ba phút ấy để thong thả bước đến một dòng suối, tận hưởng cả hành trình đi tìm nước chứ không chỉ là kết quả.",
    events:["Người gác ghi mô tả những đoàn tàu chở người lớn vội vã, không rõ đi tìm gì","Chỉ trẻ con còn áp mặt vào cửa sổ để ngắm cảnh","Người lái buôn giới thiệu viên thuốc tiết kiệm thời gian uống nước","Hoàng tử bé cho rằng mình thà dùng thời gian đó để đi tìm một dòng suối"],
    characters:["Người gác ghi","Người lái buôn"], symbols:["Sự vội vã của người lớn","Giá trị của thời gian thong thả"], planet:"Trái Đất",
    location:["🌍 Trái Đất"], keywords:["vội vã","thời gian","hiệu quả"],
    importance:"Hai cuộc gặp ngắn này bổ sung thêm một góc phê phán khác về thế giới người lớn: không chỉ bị ám ảnh bởi quyền lực hay con số, mà còn bởi tốc độ và hiệu suất — đến mức đánh đổi cả những trải nghiệm chậm rãi, giản dị mà chính hành trình mang lại." },

  { id: 20, roman: "XXIV, XXV", title: "Chiếc giếng giữa sa mạc",
    opening: "Ngày thứ tám giữa sa mạc, khi nước gần cạn, một câu nói của Hoàng tử bé bất ngờ trở thành lời tiên đoán.",
    summary: "Đây là ngày thứ tám kể từ khi máy bay của phi công gặp nạn — nước uống đã cạn. Trong lúc kiệt sức bước đi giữa đêm, Hoàng tử bé kể tiếp câu chuyện của mình và nói rằng \"chính vì con người không nhìn thấy nó nên cái làm cho sa mạc đẹp lên là một cái giếng nó ẩn giấu ở một nơi nào đó\". Không lâu sau, cả hai kỳ diệu tìm thấy một cái giếng thực sự giữa sa mạc mênh mông. Nước từ chiếc giếng ấy trở nên ngọt ngào khác thường với phi công — không phải vì bản thân nó, mà vì hành trình gian khổ và tình bạn đã dẫn họ đến đó, giống như cách những vì sao trở nên đẹp hơn vì có một điều gì đó vô hình ẩn giấu trong chúng.",
    summaryLong: "Đã là ngày thứ tám kể từ sự cố máy bay, và nước dự trữ của phi công đã cạn hoàn toàn. Cả hai — người lớn kiệt sức vì khát và cậu bé vẫn kiên nhẫn kể chuyện — cùng bước đi trong đêm, tìm kiếm một cách vô vọng. Giữa lúc mệt mỏi nhất, Hoàng tử bé, thay vì nói về nỗi khát, lại kể tiếp câu chuyện về con cáo và bông hoa của mình, rồi buông một câu vừa như triết lý vừa như một lời an ủi: điều làm cho sa mạc đẹp lên chính là một cái giếng nó ẩn giấu ở một nơi nào đó — con người không nhìn thấy nó, nhưng chính sự tồn tại vô hình ấy làm nên vẻ đẹp của cả vùng cát mênh mông. Ngay sau đó, như một phép màu, cả hai tìm thấy một cái giếng có thật giữa sa mạc — không giống những giếng ở sa mạc Sahara thường chỉ là một cái lỗ đào trong cát, mà có ròng rọc, dây thừng và thùng múc nước, giống hệt một cái giếng trong làng. Khi phi công kéo nước lên và uống, thứ nước ấy ngọt ngào một cách khác thường — không phải vì bản thân nó có gì đặc biệt, mà vì cả hành trình gian khổ, cả tình bạn nảy sinh giữa họ, đã khiến nó trở nên quý giá, giống hệt cách những vì sao trở nên đẹp hơn nhờ một điều gì đó vô hình đang ẩn giấu bên trong chúng.",
    events:["Phi công gần kiệt sức vì thiếu nước","Hoàng tử bé nói về vẻ đẹp ẩn giấu của sa mạc","Cả hai tìm thấy một chiếc giếng giữa sa mạc","Phi công cảm nhận giá trị đặc biệt của nước và của hành trình đã đưa họ đến đó"],
    characters:["Hoàng tử bé","Người phi công"], symbols:["Chiếc giếng","Vẻ đẹp ẩn giấu"], planet:"Trái Đất",
    location:["🌍 Trái Đất — sa mạc"], keywords:["giếng nước","vẻ đẹp ẩn giấu","hành trình"],
    importance:"Chương này khép lại vòng lặp của ý niệm \"nhìn bằng trái tim\" bằng một trải nghiệm cụ thể của chính người phi công — không chỉ Hoàng tử bé, mà cả người kể chuyện, giờ đây cũng cảm nhận được rằng giá trị thật của một điều gì đó nằm ở hành trình và tình cảm dẫn ta đến với nó, chứ không chỉ ở bản thân sự vật." },

  { id: 21, roman: "XXVI, XXVII", title: "Sự trở về", spoilerSensitive:true,
    opening: "Đúng một năm sau ngày rơi xuống sa mạc, Hoàng tử bé dẫn phi công quay lại đúng nơi cậu đã đến — để chuẩn bị cho một điều cậu đã hẹn trước.",
    summary: "Hoàng tử bé dẫn phi công đến đúng nơi cậu đã đáp xuống Trái Đất một năm trước — cũng là nơi cậu đã hẹn gặp lại con rắn. Cậu chuẩn bị tinh thần để \"trở về\" hành tinh của mình và bông hoa đang chờ đợi, nhưng nói rõ với phi công rằng thân xác cậu để lại sẽ chỉ như một lớp vỏ cũ kỹ, không đáng buồn, giống như người ta bỏ lại một bộ quần áo cũ. Đêm đó, con rắn cắn vào mắt cá chân cậu; Hoàng tử bé ngã xuống nhẹ nhàng như một thân cây đổ, gần như không phát ra tiếng động, vì trên cát.\n\nSáng hôm sau, phi công không tìm thấy thi thể cậu. Anh tin rằng Hoàng tử bé đã thực sự trở về hành tinh của mình. Câu chuyện khép lại với hình ảnh phi công, nhiều năm sau, mỗi khi nhìn lên bầu trời đêm đầy sao, vẫn tự hỏi liệu con cừu mà anh vẽ có ăn mất bông hoa hồng kia hay không — và với anh, đó là điều quan trọng nhất trên đời, dù chẳng ai khác hiểu vì sao.",
    summaryLong: "Sau khi chiếc máy bay được sửa xong và nước đã tìm thấy, Hoàng tử bé lặng lẽ dẫn phi công quay lại đúng nơi cậu đã hạ cánh xuống Trái Đất một năm về trước — cũng chính là nơi cậu đã hẹn gặp lại con rắn năm nào. Với vẻ nghiêm trang khác thường, cậu chuẩn bị cho phi công tinh thần về một điều sắp xảy ra: cậu sẽ \"trở về\" hành tinh của mình, nơi bông hoa đang chờ đợi, nhưng con đường trở về ấy sẽ trông giống như một cái chết. Cậu trấn an phi công rằng đừng buồn, vì thân xác cậu để lại chỉ là một lớp vỏ cũ, nặng nề, không quan trọng, giống như người ta bỏ lại một bộ quần áo cũ kỹ không cần mang theo — điều thật sự của cậu, giống như những vì sao, sẽ vẫn ở đó, chỉ là con mắt không nhìn thấy được. Đêm hôm ấy, con rắn cắn vào mắt cá chân Hoàng tử bé. Cậu ngã xuống nhẹ nhàng, gần như không một tiếng động, như một thân cây đổ xuống trên nền cát êm. Sáng hôm sau, khi phi công quay lại tìm, thân xác cậu đã không còn ở đó nữa. Không có bằng chứng nào khác, nhưng phi công chọn tin rằng Hoàng tử bé đã thật sự trở về được hành tinh của mình. Câu chuyện khép lại nhiều năm sau, với hình ảnh người phi công, mỗi khi ngước nhìn bầu trời đêm đầy sao, vẫn không thôi tự hỏi liệu con cừu mà anh từng vẽ vội trên một tờ giấy có ăn mất bông hoa hồng kia hay không — một câu hỏi tưởng như nhỏ nhặt, nhưng với anh, đó lại là điều quan trọng nhất trên đời, dù chẳng ai khác có thể hiểu vì sao.",
    events:["Hoàng tử bé và phi công quay lại đúng nơi hạ cánh năm xưa","Hoàng tử bé chuẩn bị tinh thần \"trở về\" hành tinh, an ủi phi công rằng thân xác chỉ là lớp vỏ","Con rắn cắn Hoàng tử bé trong đêm; cậu ngã xuống nhẹ nhàng, không một tiếng động","Sáng hôm sau không còn thấy thân xác cậu đâu nữa","Phi công được cứu, trở về, và nhiều năm sau vẫn dõi theo bầu trời sao, tự hỏi về số phận bông hoa và con cừu"],
    characters:["Hoàng tử bé","Người phi công","Con rắn"], symbols:["Con rắn","Sự trở về","Những vì sao","Con cừu và bông hồng"], planet:"Trái Đất",
    location:["🌍 Trái Đất — nơi gặp gỡ đầu tiên"], keywords:["trở về","chia ly","ký ức","những vì sao"],
    importance:"Đoạn kết khép lại vòng tròn của cả câu chuyện: từ một cuộc gặp gỡ giữa sa mạc đến một cuộc chia ly cũng giữa sa mạc ấy — nhưng thay vì kết thúc trong mất mát, tác phẩm chọn để lại một hình ảnh mở: những vì sao, nơi Hoàng tử bé có thể vẫn đang hiện diện, chỉ là bằng một cách khác với đôi mắt thường." },
];

const characters = [
  { name:"Hoàng tử bé", icon:"👑", role:"Trung tâm câu chuyện", desc:"Cậu bé đến từ tiểu hành tinh B-612, ngây thơ nhưng sâu sắc, luôn đặt những câu hỏi khiến người lớn phải im lặng." },
  { name:"Người phi công", icon:"🛩️", role:"Người kể chuyện", desc:"Từng từ bỏ ước mơ hội họa để trở thành phi công; gặp Hoàng tử bé khi máy bay rơi giữa Sahara." },
  { name:"Bông hoa hồng", icon:"🌹", role:"Tình yêu & sự gắn bó", desc:"Kiêu hãnh, đỏng đảnh nhưng yêu Hoàng tử bé thật lòng; là lý do cậu luôn muốn quay về." },
  { name:"Con cáo", icon:"🦊", role:"Tình bạn & trách nhiệm", desc:"Dạy Hoàng tử bé ý nghĩa của sự \"thuần hóa\" và cách nhìn bằng trái tim." },
  { name:"Con rắn", icon:"🐍", role:"Cánh cửa trở về", desc:"Sinh vật bí ẩn trên Trái Đất, nói năng như câu đố, gắn liền với đoạn kết của câu chuyện." },
  { name:"Nhà vua", icon:"👑", role:"Quyền lực hình thức", desc:"Cai trị một hành tinh trống rỗng, chỉ ra lệnh những điều tất yếu sẽ xảy ra." },
  { name:"Kẻ khoác lác", icon:"🎩", role:"Nhu cầu được ngưỡng mộ", desc:"Chỉ nghe được lời khen, sống cô độc trong nhu cầu được tán dương." },
  { name:"Người nát rượu", icon:"🍷", role:"Vòng luẩn quẩn", desc:"Uống để quên đi sự xấu hổ vì chính việc uống rượu." },
  { name:"Nhà tư sản", icon:"💰", role:"Sở hữu & con số", desc:"Đếm sao và tin rằng ghi số lên giấy nghĩa là sở hữu chúng." },
  { name:"Người thắp đèn", icon:"🏮", role:"Sự tận tụy", desc:"Người duy nhất Hoàng tử bé thấy có thể làm bạn — vì làm việc vì điều gì đó ngoài bản thân." },
  { name:"Nhà địa lý", icon:"🗺️", role:"Tri thức xa trải nghiệm", desc:"Ghi chép về thế giới nhưng chưa từng tự mình khám phá nó." },
];

const symbols = [
  { icon:"🌹", title:"Bông hoa hồng", sub:"Tình yêu & sự gắn bó",
    book:"Bông hoa không đặc biệt chỉ vì hình dáng của nó — cáo giúp Hoàng tử bé nhận ra rằng chính thời gian cậu dành để chăm sóc bông hoa mới khiến nó trở nên duy nhất, khác với 5000 bông hồng giống hệt trong khu vườn.",
    interpret:"Có thể hiểu đây là cách tác phẩm nói về bản chất của tình yêu: giá trị của một mối quan hệ không nằm ở sự hoàn hảo, mà ở công sức và thời gian ta đã bỏ ra cho nó.",
    tip:"Tình yêu, sự gắn bó, sự mong manh..." },
  { icon:"🦊", title:"Con cáo", sub:"Tình bạn & sự kết nối",
    book:"Cáo dạy Hoàng tử bé về khái niệm \"thuần hóa\" — quá trình kiên nhẫn tạo dựng mối dây ràng buộc giữa hai bên, khiến họ trở thành duy nhất đối với nhau.",
    interpret:"Nhiều người đọc xem đây là ẩn dụ cho tình bạn nói chung: tình bạn thật sự cần thời gian, sự đều đặn và không thể vội vàng.",
    tip:"Tình bạn, sự thuần hóa, trách nhiệm..." },
  { icon:"🌳", title:"Cây bao-bá", sub:"Những vấn đề nhỏ nếu bị bỏ mặc",
    book:"Cây bao-bá ban đầu rất nhỏ và dễ nhầm với cây hoa hồng, nhưng nếu không được nhổ bỏ sớm, rễ của chúng có thể lớn dần và làm nứt vỡ cả hành tinh.",
    interpret:"Có thể diễn giải như hình ảnh của những thói quen xấu, vấn đề bị trì hoãn hay trách nhiệm cá nhân bị lơ là — những nguy cơ âm thầm lớn dần nếu không được xử lý kịp thời. Đây là một cách hiểu phổ biến, không phải ý nghĩa duy nhất mà tác giả khẳng định.",
    tip:"Những vấn đề nhỏ cần được nhận diện trước khi trở nên quá lớn..." },
  { icon:"⭐", title:"Những vì sao", sub:"Ký ức và sự hiện diện của người mình yêu quý",
    book:"Ở cuối truyện, phi công nói rằng khi nhìn lên bầu trời đêm, anh sẽ luôn nghĩ đến Hoàng tử bé, như thể cậu đang cười với anh từ một trong những vì sao đó.",
    interpret:"Bầu trời sao thường được hiểu như biểu tượng cho sự hiện diện vô hình của những người ta yêu thương, dù họ không còn ở bên cạnh.",
    tip:"Ký ức, khoảng cách, sự hiện diện của người mình yêu quý..." },
  { icon:"🪐", title:"Các hành tinh", sub:"Những kiểu người lớn",
    book:"Sáu hành tinh đầu tiên Hoàng tử bé ghé thăm mỗi nơi có một người lớn duy nhất, mỗi người bị cuốn vào một nỗi ám ảnh riêng: quyền lực, sự ngưỡng mộ, rượu, sở hữu, công việc, hay tri thức xa rời thực tế.",
    interpret:"Có thể xem đây là một bộ sưu tập châm biếm về những cách người lớn tự giới hạn thế giới của mình trong một nỗi ám ảnh duy nhất, đánh mất khả năng kết nối thật sự.",
    tip:"Mỗi hành tinh, một nỗi ám ảnh, một sự cô đơn..." },
  { icon:"🧮", title:"Những con số", sub:"Khi con người đánh giá thế giới bằng số liệu",
    book:"Ngay từ chương đầu, tác phẩm chỉ ra rằng khi kể về một người bạn mới, người lớn thường hỏi tuổi tác, cân nặng, thu nhập của cha mẹ cậu ấy, thay vì hỏi giọng nói cậu ra sao hay cậu thích trò chơi gì.",
    interpret:"Đây thường được đọc như lời phê phán nhẹ nhàng đối với xu hướng đo lường giá trị con người và sự vật bằng số liệu thay vì bằng cảm xúc và trải nghiệm.",
    tip:"Con số nói được rất ít về điều thật sự quan trọng..." },
  { icon:"❤️", title:"\"Nhìn bằng trái tim\"", sub:"Cốt yếu vô hình trước mắt thường",
    book:"Trước khi chia tay, con cáo nói với Hoàng tử bé rằng người ta chỉ nhìn thấy rõ với trái tim, còn cái cốt yếu thì con mắt không nhìn thấy được — và liên hệ điều đó với thời gian cậu đã dành cho bông hoa của mình.",
    interpret:"Đây được xem là câu nói trung tâm của toàn bộ tác phẩm: những điều thật sự quan trọng — tình yêu, tình bạn, sự gắn bó — thường không thể đo đếm hay nhìn thấy bằng mắt thường, mà chỉ có thể cảm nhận.",
    tip:"Điều cốt yếu thì con mắt không thấy được..." },
  { icon:"💧", title:"Chiếc giếng giữa sa mạc", sub:"Giá trị được tạo nên bởi hành trình",
    book:"Chiếc giếng phi công và Hoàng tử bé tìm thấy sau một đêm kiệt sức trở nên ngọt ngào khác thường — không phải vì bản thân nó, mà vì hành trình gian khổ và tình bạn đã dẫn họ đến đó.",
    interpret:"Có thể đọc như hình ảnh cho việc những điều quý giá nhất thường không đến dễ dàng — chính hành trình gian nan mới là thứ làm nên giá trị của điều ta tìm được ở cuối đường.",
    tip:"Giá trị của những điều chỉ trở nên quý giá sau một hành trình..." },
];

/* ---- Ý NGHĨA — 12 chủ đề được phân tích sâu, 4 tầng mỗi chủ đề ---- */
const meanings = [
  { icon:"🌹", title:"Tình yêu không nằm ở sự hoàn hảo",
    core:"Bông hoa hồng của Hoàng tử bé không hề hoàn hảo: kiêu hãnh, hay nói dối về những chiếc gai, đòi hỏi những điều vô lý. Nếu chỉ nhìn vào những gì hoa nói, người ta dễ kết luận đây là một mối quan hệ mệt mỏi, thậm chí độc hại. Nhưng tác phẩm không dừng ở đó. Cáo, ở gần cuối truyện, chỉ ra một sự thật khác: giữa năm nghìn bông hồng giống hệt nhau trong khu vườn, bông hoa của Hoàng tử bé không đặc biệt vì hình dáng — nó đặc biệt vì cậu đã tưới nước cho nó, che chắn gió cho nó, giết những con sâu bướm cho nó, và lắng nghe cả những lời than phiền lẫn im lặng của nó. Nói cách khác, tình yêu ở đây không phải là một cảm giác dành cho một đối tượng hoàn hảo có sẵn, mà là kết quả của thời gian và công sức bỏ ra. Sự vụng về ban đầu của Hoàng tử bé — không hiểu được những lời nói mâu thuẫn của hoa — không phải là thất bại, mà là một phần tất yếu của quá trình học cách yêu.",
    layers:{
      story:"Hoàng tử bé chăm sóc một bông hoa kiêu kỳ, rời xa nó trong bối rối, rồi nhận ra giá trị thật của nó qua lời con cáo.",
      symbol:"Bông hoa đại diện cho bất kỳ người nào ta yêu thương với tất cả sự không hoàn hảo của họ, không phải một hình mẫu lý tưởng.",
      psychological:"Con người thường nhầm lẫn giữa tình yêu với sự hoàn hảo của đối tượng, trong khi thực chất tình yêu được xây bằng thời gian, sự kiên nhẫn và những lần va chạm.",
      life:"Một mối quan hệ có thể có va chạm, hiểu lầm, thậm chí kiêu kỳ — nhưng điều đó không tự động khiến nó kém giá trị hơn." },
    question:"Có ai đó trong đời bạn từng khiến bạn mệt mỏi, nhưng chính khoảng thời gian bạn dành cho họ lại là điều khiến họ trở nên không thể thay thế?",
    alternative:"Cũng có thể đọc mối quan hệ giữa Hoàng tử bé và bông hoa không phải như một hình mẫu lý tưởng cần noi theo, mà như một lời cảnh báo: đôi khi ta ở lại quá lâu với một điều gây tổn thương chỉ vì ta đã đầu tư quá nhiều vào nó — bài học không chỉ là \"ở lại vì đã bỏ công sức\", mà còn là nhận ra khi nào công sức bỏ ra cần đi kèm sự thẳng thắn và ranh giới." },

  { icon:"🦊", title:"Tình bạn và sự \"thuần hóa\"",
    core:"Con cáo không đơn giản xuất hiện để dạy Hoàng tử bé một bài học có sẵn về tình bạn. Điều quan trọng hơn nằm ở chính quá trình hình thành mối quan hệ giữa hai nhân vật. Trước khi trở nên đặc biệt với nhau, họ hoàn toàn xa lạ — một cậu bé trong hàng vạn cậu bé, một con cáo trong hàng vạn con cáo. Cáo từ chối chơi ngay lập tức, dù đang cô đơn và có lý do để muốn có bạn — vì nó hiểu rằng một mối dây ràng buộc thật sự không thể được tạo ra tức thì. Nó đòi hỏi một quy trình cụ thể: khoảng cách ban đầu, sự lặp lại đều đặn, một giờ hẹn cố định để có thể mong chờ, và sự im lặng nhiều hơn lời nói. Chính vì phải trải qua từng bước ấy, khi mối dây được tạo thành, nó mới có giá trị — và chính vì có giá trị, sự chia tay sau đó mới đau đớn, nhưng cáo vẫn chấp nhận đánh đổi, vì nó đã được ngắm nhìn màu vàng của lúa mì và nhớ đến mái tóc Hoàng tử bé mỗi khi gió thổi qua đồng.",
    layers:{
      story:"Cáo dạy Hoàng tử bé cách \"thuần hóa\" nhau qua sự kiên nhẫn, đều đặn, và một giờ hẹn cố định mỗi ngày.",
      symbol:"Quá trình thuần hóa tượng trưng cho cách một tình bạn thật sự được xây dựng — không phải bằng một khoảnh khắc, mà bằng một chuỗi những lần trở lại.",
      psychological:"Con người thường muốn có ngay một mối quan hệ gần gũi mà bỏ qua giai đoạn xây dựng lòng tin cần thiết, khiến mối quan hệ trở nên mong manh.",
      life:"Tình bạn thật sự cần thời gian, sự đều đặn, và không thể vội vàng — nhưng phần thưởng của nó là trở nên \"duy nhất\" đối với nhau." },
    question:"Bạn có đang dành đủ thời gian đều đặn cho những mối quan hệ mà bạn muốn giữ gìn, hay đang chờ chúng tự nhiên bền chặt mà không cần vun đắp?",
    alternative:"Khái niệm \"thuần hóa\" cũng có thể đọc theo một chiều khác: không chỉ là chủ động xây dựng quan hệ, mà còn là chấp nhận việc bị ràng buộc — để cho ai đó trở nên quan trọng với mình nghĩa là chấp nhận rủi ro tổn thương khi phải xa cách, và tác phẩm không né tránh điều đó." },

  { icon:"❤️", title:"Trách nhiệm với điều mình đã gắn bó",
    core:"Ngay sau khi trao cho Hoàng tử bé bí mật về việc nhìn bằng trái tim, con cáo nói thêm một điều ít được nhắc đến hơn nhưng không kém phần quan trọng: một khi đã thuần hóa điều gì, người ta mãi mãi có trách nhiệm với nó. Đây không phải một lời khuyên nhẹ nhàng, mà là một ràng buộc đạo đức: tình cảm không dừng lại ở cảm xúc, mà kéo theo nghĩa vụ. Hoàng tử bé, sau khi hiểu điều này, không còn nhìn bông hoa của mình như một gánh nặng khó chịu nữa, mà như một điều cậu đã chọn và vì thế phải chăm lo, bất kể hoa có đỏng đảnh đến đâu. Điều thú vị là trách nhiệm này không được trình bày như một sự hy sinh nặng nề, mà như hệ quả tự nhiên của tình yêu thật: nếu đã để ai đó trở nên duy nhất đối với mình, việc chăm sóc họ không còn là lựa chọn, mà là một phần của chính mối dây đó.",
    layers:{
      story:"Cáo nhắc Hoàng tử bé rằng cậu \"mãi mãi có trách nhiệm với những gì mình đã thuần hóa\" — trực tiếp áp dụng vào bông hoa cậu đã bỏ lại.",
      symbol:"Trách nhiệm ở đây là mặt còn lại của tình yêu: nếu tình yêu là lựa chọn gắn bó, trách nhiệm là điều đi kèm không thể tách rời.",
      psychological:"Nhiều người muốn tình cảm gắn bó nhưng né tránh trách nhiệm đi kèm — tác phẩm cho thấy hai điều này không thể bị chia tách.",
      life:"Một người bạn, một thú cưng, một dự án, hay một lời hứa mà ta đã đầu tư tình cảm vào đều kéo theo một trách nhiệm âm thầm cần được duy trì." },
    question:"Có điều gì bạn đã từng \"thuần hóa\" — một người, một công việc, một cam kết — mà gần đây bạn đang lơ là trách nhiệm của mình với nó?",
    alternative:"Cũng có thể đọc câu nói này như một lời cảnh tỉnh về việc gắn bó có chọn lọc: không phải mọi thứ đều đáng để thuần hóa, và một phần của trưởng thành là biết mình có đủ khả năng gánh trách nhiệm trước khi để một mối dây hình thành." },

  { icon:"👁️", title:"Nhìn bằng trái tim thay vì chỉ bằng mắt",
    core:"Câu nói của con cáo — chỉ có thể nhìn thấy rõ bằng trái tim, còn cái cốt yếu thì con mắt không nhìn thấy được — không xuất hiện đơn độc, mà là điểm hội tụ của rất nhiều tình huống trước đó trong truyện: bức vẽ con trăn bị hiểu nhầm thành cái mũ vì người lớn chỉ nhìn hình dạng bên ngoài, chiếc giếng trở nên ngọt ngào không vì bản thân nước mà vì hành trình vô hình dẫn đến nó, và bông hoa trở nên duy nhất không vì vẻ ngoài mà vì thời gian đã bỏ ra cho nó. Tất cả đều chỉ về một hướng: những gì thật sự có giá trị thường không thể đo, đếm hay chụp lại bằng mắt thường, mà chỉ hiện ra qua cảm nhận, ký ức và sự gắn bó.",
    layers:{
      story:"Con cáo trao cho Hoàng tử bé câu nói này ngay trước khi chia tay, như một món quà để cậu mang theo suốt hành trình còn lại.",
      symbol:"Đôi mắt tượng trưng cho cách nhìn duy lý, đo đếm được của người lớn; trái tim tượng trưng cho cách cảm nhận qua gắn bó và trải nghiệm.",
      psychological:"Con người dễ tin vào những gì đo lường được (thành tích, ngoại hình, con số) hơn những gì chỉ có thể cảm nhận (tình cảm, ký ức, sự tin tưởng), dù điều thứ hai thường bền vững hơn.",
      life:"Việc đánh giá một người, một công việc hay một quyết định chỉ dựa trên những gì \"nhìn thấy được\" có thể bỏ lỡ phần quan trọng nhất của nó." },
    question:"Gần đây có điều gì bạn đánh giá chỉ bằng những gì nhìn thấy được, mà có lẽ cần được nhìn lại bằng một cách khác?",
    alternative:"Cũng có thể hiểu câu nói này không phải là lời phủ nhận lý trí, mà là lời nhắc rằng lý trí và cảm nhận cần đi cùng nhau — \"nhìn bằng trái tim\" không có nghĩa là bỏ qua sự thật, mà là không để những gì đo đếm được che khuất những gì thật sự quan trọng." },

  { icon:"👨‍💼", title:"Phê phán thế giới người lớn",
    core:"Sáu hành tinh đầu tiên Hoàng tử bé ghé thăm tạo thành một chuỗi chân dung châm biếm về những kiểu người lớn: một vị vua chỉ ra lệnh những điều tất yếu để giữ ảo tưởng quyền lực, một kẻ khoác lác chỉ nghe được lời khen, một người say sưa trong một vòng luẩn quẩn không lối thoát, một nhà tư sản tin rằng ghi số lên giấy nghĩa là sở hữu, một người thắp đèn máy móc tuân lệnh dù kiệt sức, và một nhà địa lý biết rất nhiều về thế giới nhưng chưa từng bước ra khỏi bàn làm việc. Điều đáng chú ý là mỗi người trong số họ không hề xấu xa — họ chỉ đơn giản là bị giam trong một nỗi ám ảnh duy nhất đến mức đánh mất khả năng kết nối với người khác, kể cả với một cậu bé đang thật lòng tò mò về họ.",
    layers:{
      story:"Hoàng tử bé lần lượt ghé thăm sáu hành tinh, mỗi nơi chỉ có một người lớn sống cô độc với nỗi ám ảnh riêng.",
      symbol:"Mỗi hành tinh nhỏ bé, chỉ đủ chỗ cho một người, tượng trưng cho việc mỗi nỗi ám ảnh giam người ta trong một thế giới ngày càng thu hẹp.",
      psychological:"Khi một mối bận tâm (quyền lực, sự công nhận, thành tích, sở hữu) trở thành trung tâm duy nhất của cuộc sống, nó có xu hướng cô lập người ta khỏi những mối quan hệ thật.",
      life:"Không khó để nhận ra một chút bóng dáng của từng hành tinh trong chính đời sống hiện đại — trong công việc, mạng xã hội, hay cách ta đo lường thành công." },
    question:"Nếu Hoàng tử bé ghé thăm \"hành tinh\" của chính bạn hôm nay, cậu sẽ thấy bạn đang bị cuốn vào nỗi ám ảnh nào?",
    alternative:"Cũng có thể đọc các hành tinh này bằng ánh mắt cảm thông hơn là chỉ trích: mỗi người lớn ấy có lẽ đã từng là một đứa trẻ như Hoàng tử bé, và nỗi ám ảnh của họ hôm nay biết đâu bắt nguồn từ một nỗi sợ hay tổn thương nào đó chưa được kể ra." },

  { icon:"🌱", title:"Những cây bao-bá trong cuộc sống",
    core:"Việc nhổ bao-bá mỗi sáng là một hành động rất nhỏ, lặp đi lặp lại, không có gì đáng kể trong một ngày — nhưng chính vì tính chất nhỏ nhặt và dễ trì hoãn ấy mà nó trở thành một hình ảnh mạnh mẽ. Bao-bá không nguy hiểm vì bản thân nó lớn ngay từ đầu; nó nguy hiểm vì ban đầu quá nhỏ để ai bận tâm, và khi người ta nhận ra thì đã quá muộn để xử lý mà không gây thiệt hại. Tác phẩm không nói rõ bao-bá tượng trưng cho điều gì cụ thể, để ngỏ cho người đọc tự liên hệ — nhưng chính sự để ngỏ ấy khiến hình ảnh này áp dụng được cho rất nhiều loại vấn đề khác nhau trong đời sống thật.",
    layers:{
      story:"Hoàng tử bé nhổ bỏ mầm bao-bá mỗi sáng như một kỷ luật bắt buộc, vì nếu để chúng lớn, rễ cây có thể làm nứt vỡ cả hành tinh.",
      symbol:"Có thể được đọc như những vấn đề nhỏ, nếu bị bỏ mặc, sẽ trở nên nghiêm trọng và khó xử lý hơn theo thời gian.",
      psychological:"Con người thường trì hoãn việc đối diện với những điều khó chịu, một phần vì lúc mới xuất hiện, chúng có vẻ quá nhỏ để phải bận tâm ngay.",
      life:"Một thói quen xấu, một mâu thuẫn chưa nói ra, một khoản nợ, hay một tổn thương bị bỏ quên đều có thể âm thầm lớn dần nếu không ai chăm sóc đến chúng đúng lúc." },
    question:"Nếu cuộc sống của bạn cũng có những cây bao-bá, bạn đang để chúng lớn lên hay đang nhổ chúng từ khi còn nhỏ?",
    alternative:"Bao-bá cũng có thể được đọc theo một hướng ít u ám hơn: không phải mọi thứ cần nhổ bỏ đều là \"vấn đề xấu\" — đó cũng có thể là những trách nhiệm âm thầm mà bất kỳ ai gìn giữ một điều gì đó (một ngôi nhà, một mối quan hệ, một cộng đồng) đều phải duy trì đều đặn, không phải vì có nguy cơ, mà vì đó là cách để nơi mình sống luôn được chăm sóc." },

  { icon:"🏜️", title:"Sa mạc, chiếc giếng và vẻ đẹp của những điều vô hình",
    core:"Sa mạc trong tác phẩm không đơn thuần là bối cảnh — nó gần như là một nhân vật. Đó là nơi phi công đối mặt với khả năng cái chết, nơi Hoàng tử bé xuất hiện, nơi cả hai tìm thấy giếng nước, và cũng là nơi câu chuyện khép lại. Điều khiến sa mạc trở nên đẹp, theo lời Hoàng tử bé, không phải là bản thân cồn cát, mà là một cái giếng nó ẩn giấu ở một nơi nào đó — một điều con người không nhìn thấy được. Đây là một trong những hình ảnh cô đọng nhất của toàn tác phẩm: vẻ đẹp không nằm ở những gì phơi bày ngay trước mắt, mà ở khả năng một nơi tưởng như trống rỗng vẫn có thể ẩn chứa điều gì đó đáng giá, miễn là người ta tin và tiếp tục tìm kiếm.",
    layers:{
      story:"Giữa lúc kiệt sức vì thiếu nước, Hoàng tử bé nói về vẻ đẹp ẩn giấu của sa mạc, ngay trước khi cả hai kỳ diệu tìm thấy một chiếc giếng thật.",
      symbol:"Chiếc giếng ẩn trong sa mạc tượng trưng cho những điều quý giá không lộ ra ngay lập tức, chỉ những ai kiên trì tìm kiếm mới chạm tới được.",
      psychological:"Niềm tin rằng một nơi tưởng như cằn cỗi vẫn có thể chứa đựng điều gì đó ý nghĩa giúp con người có động lực tiếp tục, ngay cả trong những giai đoạn khó khăn nhất.",
      life:"Những giai đoạn trống rỗng, mệt mỏi, hay bế tắc trong đời không hẳn là vô nghĩa — đôi khi chính chúng lại dẫn đến điều đáng giá nhất, nếu ta không dừng bước quá sớm." },
    question:"Bạn có đang đi qua một \"sa mạc\" nào đó của riêng mình, và có nghĩ rằng bên dưới nó vẫn có thể có một chiếc giếng đang chờ được tìm thấy?",
    alternative:"Hình ảnh này cũng có thể đọc theo hướng thực tế hơn: không phải mọi sa mạc đều có giếng, và tác phẩm không hứa hẹn một cái kết có hậu cho mọi khó khăn — điều nó gợi ra chỉ là cách nhìn khiến hành trình có ý nghĩa, không phải một sự đảm bảo về kết quả." },

  { icon:"⭐", title:"Ký ức và sự hiện diện của người đã rời xa",
    core:"Ở những trang cuối, phi công nói rằng anh sẽ không bao giờ có thể nhìn bầu trời đêm giống như trước nữa — với anh, tất cả các vì sao giờ đây đều mang một ý nghĩa khác, vì biết đâu Hoàng tử bé đang cười với anh từ một trong số đó. Đây là một trong những hình ảnh giàu cảm xúc nhất của toàn tác phẩm: cái chết, hay sự chia ly, không được miêu tả như một sự biến mất tuyệt đối, mà như một sự chuyển hoá — người ra đi vẫn tiếp tục hiện diện, không phải bằng thân xác, mà bằng cách họ đã thay đổi cách người ở lại nhìn thế giới xung quanh.",
    layers:{
      story:"Phi công, sau khi Hoàng tử bé rời đi, không còn nhìn bầu trời đêm như trước — mỗi vì sao đều có thể là nơi cậu đang ở.",
      symbol:"Những vì sao trở thành nơi lưu giữ ký ức về người đã rời xa — không thể chạm vào, nhưng luôn ở đó, mỗi đêm.",
      psychological:"Cách con người đối diện với mất mát thường không phải bằng việc quên đi, mà bằng việc gắn ký ức về người đã mất vào những điều quen thuộc trong đời sống hằng ngày.",
      life:"Một người đã rời xa — vì khoảng cách, vì chia tay, hay vì cái chết — có thể vẫn tiếp tục hiện diện trong cách ta nhìn một số điều quen thuộc, dù họ không còn ở đó theo nghĩa vật lý." },
    question:"Có điều gì quen thuộc trong đời sống hằng ngày của bạn — một bài hát, một con đường, một mùa trong năm — đã mang một ý nghĩa khác kể từ khi ai đó quan trọng rời xa bạn?",
    alternative:"Cũng có thể đọc điều này một cách thận trọng hơn: gán ý nghĩa cho những sự vật quen thuộc là một cách con người tự an ủi mình trước mất mát, chứ tác phẩm không khẳng định có một sự hiện diện siêu nhiên thật sự nào ở đó — điều quan trọng là cách làm ấy giúp nỗi đau trở nên có thể mang theo được." },

  { icon:"🏠", title:"Khái niệm \"nhà\" và mong muốn trở về",
    core:"Toàn bộ hành trình của Hoàng tử bé, dù trải dài qua bảy hành tinh, luôn hướng về một điểm duy nhất: trở về với bông hoa của mình trên B-612. Ngay cả khi đang mải mê khám phá, nỗi day dứt về việc con cừu có thể ăn mất bông hoa chưa bao giờ rời khỏi cậu. \"Nhà\", trong tác phẩm, không được định nghĩa bằng một địa điểm hay một hành tinh cụ thể, mà bằng sự tồn tại của một điều — hay một ai đó — đang chờ đợi mình quay lại. Điều này giải thích vì sao, dù đã khám phá được rất nhiều, điều duy nhất Hoàng tử bé thật sự muốn ở cuối hành trình chỉ là được trở về.",
    layers:{
      story:"Xuyên suốt hành trình, Hoàng tử bé không ngừng nghĩ về bông hoa mình đã để lại, và cuối cùng chọn \"trở về\" hành tinh của mình.",
      symbol:"B-612 không chỉ là một hành tinh, mà là biểu tượng cho bất kỳ nơi nào có người hay điều gì đang chờ đợi ta.",
      psychological:"Cảm giác thuộc về một nơi thường gắn liền không phải với địa lý, mà với những mối gắn bó ta đã xây dựng ở đó.",
      life:"\"Nhà\", với nhiều người, không phải là nơi sinh ra hay nơi đang sống, mà là nơi có người hoặc điều gì đó khiến ta muốn quay lại." },
    question:"Nếu phải trả lời ngay bây giờ: điều gì, hay ai, chính là \"bông hoa\" khiến bạn luôn muốn tìm đường trở về?",
    alternative:"Có thể đọc mong muốn trở về này không phải như một sự trốn tránh thế giới rộng lớn, mà như một sự cân bằng cần thiết: khám phá và trở về không loại trừ nhau, và chính việc có một nơi để quay về mới giúp một hành trình dài trở nên an toàn để thực hiện." },

  { icon:"⏳", title:"Giá trị của thời gian thong thả",
    core:"Người lái buôn bán viên thuốc giúp tiết kiệm năm mươi ba phút mỗi tuần, người gác ghi kể về những đoàn tàu chở đầy người lớn vội vã không rõ đi tìm gì, và đối lập với tất cả, chỉ có trẻ con vẫn áp mặt vào cửa kính để ngắm cảnh — ba chi tiết nhỏ này gộp lại thành một lời quan sát tinh tế về cách người lớn đối xử với thời gian: luôn tìm cách rút ngắn nó, tiết kiệm nó, tối ưu nó, mà quên mất rằng đôi khi chính khoảng thời gian tưởng như \"lãng phí\" — như tự mình đi bộ đến một dòng suối — mới là phần đáng sống nhất của một trải nghiệm.",
    layers:{
      story:"Hoàng tử bé cho rằng nếu là mình, cậu thà dùng năm mươi ba phút tiết kiệm được để thong thả đi tìm một dòng suối, thay vì uống viên thuốc giải khát.",
      symbol:"Dòng suối được tìm bằng chính đôi chân tượng trưng cho những trải nghiệm chỉ có giá trị khi được sống trọn vẹn, không thể rút gọn.",
      psychological:"Xu hướng muốn tối ưu hoá mọi khoảnh khắc có thể khiến con người đánh mất chính những trải nghiệm làm nên ý nghĩa của khoảnh khắc đó.",
      life:"Không phải lúc nào tiết kiệm thời gian cũng là lựa chọn tốt hơn — đôi khi con đường chậm rãi mới là phần đáng nhớ, chứ không chỉ là điểm đến." },
    question:"Gần đây, có việc gì bạn đã cố gắng làm thật nhanh, mà nhìn lại, có lẽ đáng được làm chậm rãi hơn?",
    alternative:"Cũng cần công nhận rằng không phải sự vội vã nào cũng đáng bị phê phán — với nhiều người, tốc độ và hiệu quả là điều kiện cần để có đủ thời gian dành cho những điều họ thật sự coi trọng; vấn đề không phải là nhanh hay chậm, mà là nhanh và chậm được dùng cho điều gì." },

  { icon:"🤝", title:"Sự cô đơn giữa con người",
    core:"Một nghịch lý xuyên suốt tác phẩm là: càng đông người, dường như càng dễ cô đơn. Trái Đất, với hàng tỷ người lớn, lại là nơi Hoàng tử bé đáp xuống một mình giữa sa mạc vắng lặng, phải trèo núi cao chỉ để nghe tiếng vọng của chính mình. Mỗi người lớn cậu gặp trên sáu hành tinh trước đó cũng sống hoàn toàn đơn độc, dù bận rộn với những mối bận tâm riêng. Ngay cả những đoàn tàu chở đầy hành khách cũng chỉ là những con người vội vã lướt qua nhau mà không thực sự kết nối. Sự cô đơn trong tác phẩm không đến từ việc thiếu người xung quanh, mà từ việc thiếu những mối dây ràng buộc thật sự — chính điều mà khái niệm \"thuần hóa\" của con cáo cố gắng khắc phục.",
    layers:{
      story:"Từ nhà vua cô độc đến người phi công một mình giữa sa mạc, gần như mọi nhân vật trong truyện đều sống hoặc gặp gỡ trong sự cô đơn.",
      symbol:"Những hành tinh nhỏ bé, chỉ đủ chỗ cho một người, là hình ảnh cô đọng nhất cho sự cô lập giữa một vũ trụ đông đúc.",
      psychological:"Có mặt giữa đám đông không đồng nghĩa với việc không cô đơn — cô đơn thường đến từ việc thiếu những mối liên kết có chiều sâu, chứ không phải thiếu số lượng người xung quanh.",
      life:"Giữa một thế giới ngày càng kết nối bằng công nghệ, cảm giác cô đơn vẫn có thể tồn tại nếu những kết nối ấy không đi kèm với sự \"thuần hóa\" thật sự — thời gian, sự đều đặn, sự lắng nghe." },
    question:"Trong những mối quan hệ hiện tại của bạn, đâu là mối quan hệ có \"số lượng\" tương tác nhiều nhất, và đâu là mối quan hệ có chiều sâu thật sự?",
    alternative:"Cũng có thể đọc sự cô đơn của các nhân vật người lớn không chỉ như một điều đáng buồn, mà như điều kiện cần thiết để họ — và người đọc — nhận ra giá trị của một mối dây ràng buộc thật sự, khi cuối cùng nó xuất hiện." },

  { icon:"🐍", title:"Cái chết, sự trở về và chia ly",
    core:"Phần kết của tác phẩm không mô tả cái chết theo cách thông thường. Con rắn — sinh vật có thể \"đưa ai đó trở về nơi họ đã đến\" — trở thành phương tiện cho một sự ra đi được đóng khung như một sự \"trở về\", chứ không phải một sự kết thúc. Hoàng tử bé chủ động trấn an phi công rằng thân xác cậu để lại chỉ là một lớp vỏ không quan trọng, giống như một bộ quần áo cũ. Cách viết này không né tránh nỗi đau của sự chia ly — phi công vẫn buồn, vẫn tự hỏi về số phận bông hoa nhiều năm sau — nhưng nó mở ra một khả năng khác để nhìn về mất mát: không phải như một sự biến mất tuyệt đối, mà như một sự tiếp tục tồn tại theo một cách khác, ở một nơi mắt thường không nhìn thấy được.",
    layers:{
      story:"Hoàng tử bé chọn để con rắn đưa mình \"trở về\" hành tinh của mình, sau khi chuẩn bị tinh thần cho phi công.",
      symbol:"Con rắn, dù xuất hiện gắn liền với cái chết, lại được gán cho vai trò của một \"cánh cửa trở về\" hơn là một sự huỷ diệt.",
      psychological:"Cách con người đối diện với ý niệm về cái chết hay sự chia ly thường cần một khung diễn giải để có thể chịu đựng được — ở đây, khung diễn giải đó là sự trở về, không phải sự kết thúc.",
      life:"Đối diện với một sự mất mát, đôi khi cách ta kể lại câu chuyện về nó — như một sự trở về, một sự tiếp tục theo cách khác — có thể giúp nỗi đau trở nên mang vác được, dù không làm nó biến mất." },
    question:"Nếu phải kể lại một mất mát nào đó trong đời mình theo một cách khác — không phải là kết thúc mà là một dạng \"trở về\" — bạn sẽ kể câu chuyện đó như thế nào?",
    alternative:"Đây cũng là đoạn gây tranh cãi nhiều nhất trong các cách đọc tác phẩm: một số người đọc xem đây thuần túy là hình ảnh văn học về sự tiếp nối tinh thần, trong khi số khác đọc nó theo hướng gần với niềm tin tôn giáo hoặc tâm linh về một đời sống sau cái chết — tác phẩm để ngỏ, không khẳng định cách đọc nào là duy nhất đúng." },
];

const closingQuestions = [
  "Ta đang nhìn thế giới bằng đôi mắt của mình, hay bằng những tiêu chuẩn mà người khác đặt ra?",
  "Điều gì trong cuộc đời ta đang trở thành một cây bao-bá?",
  "Ai là bông hồng mà ta đã dành thời gian để trở nên có trách nhiệm?",
  "Ta có đang quá bận rộn để nhận ra điều thực sự quan trọng?",
  "Nếu phải rời đi hôm nay, điều gì khiến ta muốn quay trở về?",
  "Ta còn nhớ đứa trẻ mà mình từng là không?",
];

const adultViews = [
  { icon:"🧒", title:"Trẻ em nhìn thấy gì?", text:"Một câu chuyện phiêu lưu kỳ lạ và dễ thương: một cậu bé đến từ một hành tinh nhỏ, gặp một con cừu, một bông hoa và một con cáo biết nói." },
  { icon:"🧑", title:"Người trưởng thành nhìn thấy gì?", text:"Một lời nhắc rằng mình đã đánh đổi bao nhiêu sự hồn nhiên để đổi lấy những con số, deadline và trách nhiệm — và có lẽ đã quên mất cách nhìn bằng trái tim." },
  { icon:"💞", title:"Một người đang yêu nhìn thấy gì?", text:"Câu chuyện về bông hoa hồng có thể trở thành tấm gương phản chiếu chính mối quan hệ của họ — cả sự vụng về lẫn giá trị của thời gian đã cùng nhau trải qua." },
  { icon:"🥀", title:"Một người từng chia tay nhìn thấy gì?", text:"Cuộc chia ly giữa Hoàng tử bé và bông hoa, hay đoạn kết với con rắn, có thể chạm đến một nỗi đau rất riêng về việc phải rời xa điều mình từng thuần hóa." },
  { icon:"🌙", title:"Một người cô đơn nhìn thấy gì?", text:"Có thể nhận ra chính mình trong hình ảnh những hành tinh nhỏ bé, nơi mỗi người lớn sống một mình với nỗi ám ảnh riêng — và trong lời mời gọi của con cáo về việc dám để ai đó bước vào." },
  { icon:"🌱", title:"Một người đang trưởng thành nhìn thấy gì?", text:"Câu chuyện có thể trở thành một lời nhắc dịu dàng: trưởng thành không nhất thiết phải đánh đổi bằng việc đánh mất khả năng nhìn bằng trái tim." },
];

const moments = [
  { icon:"🐑", title:"Con cừu trong chiếc hộp", text:"Bất lực vì không vẽ được cừu, phi công vẽ một chiếc hộp — và đó lại là bức vẽ duy nhất khiến Hoàng tử bé hài lòng.", chapterId:2 },
  { icon:"🌇", title:"Bốn mươi bốn lần hoàng hôn", text:"Một con số nhỏ tiết lộ một nỗi buồn lớn mà Hoàng tử bé chưa từng nói ra bằng lời.", chapterId:6 },
  { icon:"🌹", title:"Lời thú nhận của bông hoa", text:"Ngay trước phút chia tay, bông hoa gạt bỏ vẻ kiêu kỳ để nói ra điều nó đã giấu suốt bấy lâu.", chapterId:9 },
  { icon:"🪐", title:"Sáu hành tinh, sáu người lớn", text:"Mỗi hành tinh chỉ có một cư dân — và mỗi người lại bị giam trong một nỗi ám ảnh của riêng mình.", chapterId:13 },
  { icon:"🌷", title:"Vườn năm nghìn bông hồng", text:"Cú sốc lớn nhất hành trình: bông hoa cậu nghĩ là duy nhất hoá ra chỉ là một trong hàng ngàn bông hồng giống hệt.", chapterId:17 },
  { icon:"🦊", title:"\"Xin hãy thuần hóa tôi\"", text:"Lời đề nghị của con cáo mở ra bài học quan trọng nhất của toàn bộ cuốn sách.", chapterId:18 },
  { icon:"💧", title:"Chiếc giếng giữa đêm sa mạc", text:"Một chiếc giếng kỳ diệu xuất hiện đúng lúc kiệt sức nhất — và trở nên ngọt ngào vì cả một hành trình đã dẫn tới nó.", chapterId:20 },
  { icon:"⭐", title:"Những vì sao biết cười", text:"Phi công không còn nhìn bầu trời đêm như trước — mỗi ngôi sao giờ đây có thể là nơi Hoàng tử bé đang mỉm cười.", chapterId:21 },
  { icon:"🐍", title:"Sự trở về lặng lẽ", text:"Một cái ngã xuống nhẹ nhàng, gần như không tiếng động — và một sáng hôm sau không còn dấu vết nào để lại.", chapterId:21 },
];

const journeyLoop = [
  { em:"🌌", label:"BẦU TRỜI", tip:"Nơi mọi thứ bắt đầu và cũng là nơi mọi thứ quay về." },
  { em:"👦", label:"HOÀNG TỬ BÉ", tip:"Cậu bé đến từ B-612, mang theo một câu hỏi ngây thơ và một trái tim gắn bó." },
  { em:"🪐", label:"HÀNH TRÌNH", tip:"Bảy hành tinh, bảy kiểu người lớn, và một cậu bé đang tìm câu trả lời." },
  { em:"🌹", label:"TÌNH YÊU", tip:"Bông hoa hồng — không hoàn hảo, nhưng trở nên duy nhất vì thời gian đã dành cho nó." },
  { em:"🦊", label:"TÌNH BẠN", tip:"Con cáo và bài học về sự thuần hóa, về việc nhìn bằng trái tim." },
  { em:"💧", label:"SỰ SỐNG", tip:"Chiếc giếng giữa sa mạc — giá trị được tạo nên bởi cả một hành trình gian khổ." },
  { em:"⭐", label:"SỰ CHIA LY", tip:"Một cuộc trở về được kể lại nhẹ nhàng như một thân cây đổ xuống trên cát." },
  { em:"🌌", label:"KÝ ỨC", tip:"Và cuối cùng, tất cả trở lại bầu trời — nơi một vì sao nào đó có thể đang mỉm cười." },
];

const authorTimeline = [
  { year:"1900", text:"Antoine de Saint-Exupéry sinh ra tại Lyon, Pháp." },
  { year:"1926", text:"Trở thành phi công (Aviateur), bắt đầu sự nghiệp bay thư và bay đường dài." },
  { year:"1929", text:"Xuất bản \"Courrier Sud\" (Chuyến thư miền Nam)." },
  { year:"1931", text:"Xuất bản \"Vol de nuit\" (Bay đêm)." },
  { year:"1939", text:"Xuất bản \"Terre des Hommes\" (Cõi người ta)." },
  { year:"1942", text:"Xuất bản \"Pilote de Guerre\" (Phi công thời chiến)." },
  { year:"1943", text:"Xuất bản \"Le Petit Prince\" (Hoàng tử bé), viết trong thời gian lưu vong tại Hoa Kỳ." },
  { year:"1944", text:"Mất tích cùng máy bay trên vùng biển Địa Trung Hải ngày 31 tháng 7, khi đang làm nhiệm vụ trinh sát cho Không quân Pháp Tự do." },
];

const sourceListData = [
  { label:"Bản dịch tiếng Việt tham chiếu ban đầu", detail:"NXB Kim Đồng, 2012 (dùng để đối chiếu cấu trúc chương, không sao chép nguyên văn)." },
  { label:"Nguyên tác", detail:"Antoine de Saint-Exupéry, \"Le Petit Prince\", xuất bản lần đầu 1943." },
  { label:"Tiểu sử tác giả", detail:"Tổng hợp từ các nguồn tiểu sử công khai về Antoine de Saint-Exupéry — nên được người đọc kiểm chứng thêm với các nguồn học thuật." },
  { label:"Hình ảnh minh họa", detail:"Trang này không sử dụng lại tranh minh họa gốc của sách; toàn bộ hình ảnh trang trí là biểu tượng/đồ họa được tạo mới, lấy cảm hứng từ bầu trời sao và sa mạc." },
];
